<div id="wrapper">
	<?php include_once('navigation.phtml');?>  
	<div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12"> 
                <h1 class="page-header">Admin</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>    
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
               <?php
               if($task=='add'){  
                   include_once('admin-add.phtml'); 
               }elseif($task=='edit'){
                   include_once('admin-edit.phtml');
               }else{
                   include_once('admin-list.phtml');
               } 
               ?>
            </div>
            <!-- /.col-lg-12 -->
        </div>
	</div>
</div>