<div class="panel panel-default">
    <div class="panel-heading">  
        New Admin
        <a href="<?php echo $this->url('index').'admin/admin/';?>" class="btn btn-success btn-xs pull-right"><i class="fa fa-undo" aria-hidden="true"></i>Back</a>
    </div>
    <div class="panel-body"> 
        <form action="<?php echo $this->url('index').'admin/admin/?task=add';?>" enctype="multipart/form-data" name="registration" id="registration" method="post">
        	<div class="box-body">
            	<div class="form-group">
                  	<label>Level</label>
                  	<select class="form-control" name="admin[level]">
                    	<option value="1">Super Admin</option>
                        <option value="2" selected>Admin</option>
                    </select>
                </div>  
        		<div class="form-group">
          			<label for="exampleInputEmail1">Name</label>
          			<input type="text" class="form-control" id="name" name="admin[name]" placeholder="Name">
        		</div>
                <div class="form-group">
          			<label for="exampleInputEmail1">Email</label>
          			<input type="email" class="form-control" id="email" name="admin[email]" placeholder="Email">
        		</div>
                <div class="form-group">
          			<label for="exampleInputEmail1">Password</label>
          			<input type="password" class="form-control" id="password" name="admin[password]" placeholder="Password">
        		</div>  
                <div class="form-group">
          			<label for="exampleInputEmail1">Phone</label>
          			<input type="text" class="form-control" id="phone" name="admin[phone]" placeholder="Phone">
        		</div>
        		<div class="form-group">
          			<label for="exampleInputFile">Image size:200x200px</label> 
          			<input type="file" id="pic" name="pic" onchange="imagePreview(this,'img-preview', 100)">
        			<div id="img-preview"></div>   
        		</div>  
                <div class="form-group"> 
                    <label for="active">Status</label><br> 
          			<input type="checkbox" name="active" id="active" value="0">     
        		</div>    
      		</div><!-- /.box-body -->
            <hr />
      		<div class="box-footer">
        		<button type="submit" class="btn btn-primary">Submit</button>
      		</div>
    	</form> 
    </div> 
</div>
<script type="text/javascript">
var url = "<?=$this->url('index').'admin/admin/?task=checkEmail';?>";  
$(function() {
  $("form[name='registration']").validate({ 
    rules: { 
     'admin[name]': {   
        required: true,
        minlength: 1
     },
     'pic': "required",
     'admin[email]':{  
        required: true, 
        email: true, 
        remote: 
        { 
            url: url,
            type: "post",  
            data:{
               'email':function()  
                {
                    return $('#email').val(); 
                }
           },  
           complete: function(data)  
            {
                console.log(data);
            }
        }
      },  
      'admin[password]': { 
        required: true,
        minlength: 5
      }
    },
    messages: { 
      'admin[name]': "Please enter your name", 
      'admin[password]': {  
        required: "Please provide a password",
        minlength: "Your password must be at least 5 characters long"
      },
      'admin[email]': {  
        required: "Please enter a valid email address.",   
        remote: function() { return $.validator.format("This email is not available.", $("#email").val()) } 
      },   
      'pic': "Please enter image profile" 
    },
    submitHandler: function(form) {
      form.submit();
    }
  });
});
</script>