<div class="panel panel-default">
    <div class="panel-heading">  
        Edit Admin
        <?php
        if($admin->level==1){  
        ?>
        <a href="<?php echo $this->url('index').'admin/admin/';?>" class="btn btn-success btn-xs pull-right"><i class="fa fa-undo" aria-hidden="true"></i>Back</a>
        <?php  
        } 
        ?>
    </div>
    <div class="panel-body"> 
        
        <form action="<?php echo $this->url('index').'admin/admin/'.$id.'?task=edit';?>" enctype="multipart/form-data" name="registration" id="registration" method="post">
        	<div class="box-body">
            	<div class="form-group">  
                  	<label>Level</label> 
                  	<select class="form-control" name="admin[level]">
                    	<option value="1" <?=($detail['level']==1)?'selected':'';?>>Super Admin</option>
                        <option value="2" <?=($detail['level']==2)?'selected':'';?>>Admin</option>
                    </select>
                </div>   
        		<div class="form-group">
          			<label for="exampleInputEmail1">Name</label>
          			<input type="text" class="form-control" id="name" name="admin[name]" placeholder="Name" value="<?=(!empty($detail['name']))?$detail['name']:'';?>">
        		</div>
                <div class="form-group">
          			<label for="exampleInputEmail1">Email</label>
          			<input type="email" class="form-control" id="email" name="admin[email]" placeholder="Email" value="<?=(!empty($detail['email']))?$detail['email']:'';?>">
        		</div>
                <div class="form-group">
          			<label for="exampleInputEmail1">Password</label>
          			<input type="password" class="form-control" id="password" name="admin[password]" placeholder="Password" value=""> 
        		</div>  
                <div class="form-group">
          			<label for="exampleInputEmail1">Phone</label> 
          			<input type="text" class="form-control" id="phone" name="admin[phone]" placeholder="Phone" value="<?=(!empty($detail['phone']))?$detail['phone']:'';?>"> 
        		</div>
        		<div class="form-group"> 
          			<label for="exampleInputFile">Image size:200x200px</label> 
          			<input type="file" id="pic" name="pic" onchange="imagePreview(this,'img-preview', 100)">
        			<div id="img-preview">
        			    <?php
        			    if(!empty($detail['image'])){     
        			    ?>
        			    <br> 
        			    <img src="<?php echo $urlFile.'/admin/'.$detail['image'];?>" style="max-width:200px;" /> 
        			    <?php
        			    } 
        			    ?>
        			</div>   
        		</div>  
                <div class="form-group">   
                    <label for="active">Status</label><br>
          			<input type="checkbox" name="active" id="active" value="<?=(!empty($detail['active']))?$detail['active']:'';?>" <?=($detail['active']==1)?'checked':'';?>>       
        		</div>    
      		</div><!-- /.box-body --> 
            <hr /> 
      		<div class="box-footer">
        		<button type="submit" class="btn btn-primary">Submit</button>
      		</div>
    	</form> 
    </div> 
</div>
<script type="text/javascript">  
$(function() {
  $("form[name='registration']").validate({ 
    rules: {
     'admin[name]': "required", 
     'admin[email]': { 
        required: true,
        email: true
      }
    }, 
    messages: { 
      'admin[name]': "Please enter your name",
      'admin[email]': "Please enter a valid email address" 
    },
    submitHandler: function(form) {
      form.submit();
    }
  });
});
</script>