<div class="panel panel-default">
    <div class="panel-heading">  
        New Blog
        <a href="<?php echo $this->url('index').'admin/blog/';?>" class="btn btn-success btn-xs pull-right"><i class="fa fa-undo" aria-hidden="true"></i>Back</a>
    </div>
    <div class="panel-body"> 
        <form action="<?php echo $this->url('index').'admin/blog/?task=add';?>" enctype="multipart/form-data" name="registration" id="registration" method="post">
        	<div class="box-body">
            	 
        		<div class="form-group">
          			<label for="name">Title</label>
          			<input type="text" class="form-control" id="name" name="blog[name]" placeholder="title">
        		</div>
        		<div class="form-group">
          			<label for="pic">Image size:480x480px</label>  
          			<input type="file" id="pic" name="pic" onchange="imagePreview(this,'img-preview', 100)">
        			<div id="img-preview"></div>    
        		</div> 
        		<div class="form-group">
          			<label for="detail">Detail Short</label>   
          		    <textarea name="blog[detail_short]" class="form-control summernote" id="detail_short" rows="5"></textarea>  
          		</div>
        		<div class="form-group"> 
          			<label for="detail">Detail</label>   
          		    <textarea name="blog[detail]" class="form-control summernote" id="detail" rows="5"></textarea>  
          		</div> 
                <div class="form-group"> 
                    <label for="active">Status</label><br> 
          			<input type="checkbox" name="active" id="active" value="0">     
        		</div>     
      		</div><!-- /.box-body -->
            <hr /> 
      		<div class="box-footer">
        		<button type="submit" class="btn btn-primary">Submit</button>
      		</div>
    	</form> 
    </div> 
</div>
<script type="text/javascript">
var url = "<?=$this->url('index').'admin/blog/?task=checkName';?>";  
$(function() {
  $("form[name='registration']").validate({  
    rules: {
     'blog[name]': { 
        required: true, 
        minlength: 2,
        remote: 
        { 
            url: url,
            type: "post", 
            data:{
               'name':function()
                {
                    return $('#name').val(); 
                }
           },  
           complete: function(data)  
            {
                console.log(data);
            }
        }
      }, 
     'pic': "required", 
    },
    messages: {  
      'blog[name]':{  
        required: "Please enter your blog name.",  
        remote: function() { return $.validator.format("This name is not available.", $("#name").val()) } 
      },
      'pic': "Please enter image blog" 
    },
     submitHandler: function(form)
     {
        form.submit();
     } 
  }); 
});
</script> 