<div class="panel panel-default">
    <div class="panel-heading">  
        Edit Contract
        <a href="<?php echo $this->url('index').'admin/contract/';?>" class="btn btn-success btn-xs pull-right"><i class="fa fa-undo" aria-hidden="true"></i>Back</a>
    </div>
    <div class="panel-body">   
        
        <form action="<?php echo $this->url('index').'admin/contract/'.$id.'?task=edit';?>" enctype="multipart/form-data" name="contract" id="contract" method="post">
        	<div class="box-body">
        	    <?php 
        	    //print_r($ar_status);  
        	    if(!empty($result)){
        	    ?>
        	    <div class="alert alert-success fade in alert-dismissable" style="margin-top:18px;">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                    <strong>Success!</strong> Contract successfuly. 
                </div>
        	    <?php
        	    }
        	    ?> 
        	    <div class="form-group">  
          			<label for="project_name">Project Name</label>    
          			<input type="text" class="form-control" id="project_name" name="contract[project_name]" placeholder="Project Name" value="<?=(!empty($detail['project_name']))?$detail['project_name']:'';?>"> 
        		</div>
        		
        		<div class="form-group"> 
          			<label for="pic">file</label>    
          			<input type="file" id="pic" name="pic">  
          			<?php
          			if(!empty($detail['contract_img'])){  
          			?>
          			<div style="display:block;margin-top:10px;"><a class="btn btn-primary btn-xs" href="<?=$urlFile;?>/contract/<?=$detail['contract_img'];?>" download=""><i class="fa fa-download" aria-hidden="true"></i>  Download</a></div>
        		    <?php
          			} 
        		    ?>
        		</div>
        		
        		<div class="form-group">
          			<label for="total_price">Price</label>   
          			<input type="number" class="form-control" id="total_price" name="contract[total_price]" placeholder="Price" value="<?=(!empty($detail['total_price']))?$detail['total_price']:'';?>"> 
        		</div> 
        		
        		<div class="form-group">
          			<label for="start_date">Start Date</label>   
          			<input type="text" class="form-control" id="start_date" name="contract[start_date]" placeholder="Start Date" value="<?=(!empty($detail['start_date']))?$detail['start_date']:'';?>" readonly> 
        		</div>
        		
        		<div class="form-group">
          			<label for="end_date">End Date</label>   
          			<input type="text" class="form-control" id="end_date" name="contract[end_date]" placeholder="End Date" value="<?=(!empty($detail['end_date']))?$detail['end_date']:'';?>" readonly> 
        		</div>
        		
        		<div class="form-group"> 
          			<label for="serial_number">Serial No.</label>    
          			<input type="number" class="form-control" id="serial_number" name="contract[serial_number]" placeholder="Serial No." value="<?=(!empty($detail['serial_number']))?$detail['serial_number']:'';?>"> 
        		</div> 
        		
        		<div class="form-group">  
          			<label for="contract_name">Name</label>    
          			<input type="text" class="form-control" id="contract_name" name="contract[contract_name]" placeholder="Name" value="<?=(!empty($detail['contract_name']))?$detail['contract_name']:'';?>"> 
        		</div>
        		
        		<div class="form-group">  
          			<label for="contract_company">Company</label>    
          			<input type="text" class="form-control" id="contract_company" name="contract[contract_company]" placeholder="Company" value="<?=(!empty($detail['contract_company']))?$detail['contract_company']:'';?>"> 
        		</div>
        		
        		<div class="form-group">  
          			<label for="company_address">Address</label> 
          			<textarea name="contract[company_address]" class="form-control summernote" id="company_address" rows="5"><?=(!empty($detail['company_address']))?$detail['company_address']:'';?></textarea>
          		</div>
        		
        		<div class="form-group">
          			<label for="contract_phone">Mobile number</label>  
          			<input type="number" class="form-control" id="price" name="contract[contract_phone]" placeholder="Mobile number" value="<?=(!empty($detail['contract_phone']))?$detail['contract_phone']:'';?>"> 
        		</div> 
        		
        		<div class="form-group"> 
          			<label for="contract_landline_phone">Land line phone</label>  
          			<input type="number" class="form-control" id="contract_landline_phone" name="contract[contract_landline_phone]" placeholder="Land line phone" value="<?=(!empty($detail['contract_landline_phone']))?$detail['contract_landline_phone']:'';?>"> 
        		</div> 
        		  
        		<div class="form-group">  
          			<label for="contract_email">Email Supplier</label>     
          			<input type="email" class="form-control" id="contract_email" name="contract[contract_email]" placeholder="Email Supplier" value="<?=(!empty($detail['contract_email']))?$detail['contract_email']:'';?>"> 
        		</div>
        		
                <div class="form-group">    
                    <label for="active">Status</label><br>   
                    <?php  
                    //0=pending, 1=accepted(supplier accepted), 2=start, 3=done, 4=looking for supplier, 5=paid, 6=waiting for money
                    ?>
          			<select id="status" name="contract[status]" class="form-control">     
          			    <?php
          			    if(!empty($ar_status)){ 
          			        foreach($ar_status as $key=>$value){    
          			    ?>
          			    <option value="<?=$key?>" <?=($detail['status']==$key)?'selected':'';?>><?=$value;?></option> 
          			    <?php
          			        } 
          			    }
          			    ?>
          			</select>      
        		</div> 
        		
      		</div><!-- /.box-body -->  
            <hr />  
      		<div class="box-footer">
        		<button type="submit" class="btn btn-primary">Submit</button>
      		</div>
    	</form> 
    </div> 
</div>
<script type="text/javascript">   
 
/************* datepicker rank *****************/
var date;
$(function() {
      $('#start_date').datepicker({ 
            minDate: 0,  
            changeMonth: true,
            changeYear: true,
            format: 'yyyy-mm-dd',
            onSelect: function(dateStr) {     
                  date = $(this).datepicker('getDate');
                  if (date) {
                        date.setDate(date.getDate() + 1);
                  }     
                  //console.log(date); 
                  $('#end_date').datepicker('option', 'minDate', date);
            }
      }); 
      $('#end_date').datepicker({ 
            minDate: 0,  
            changeMonth: true,
            changeYear: true, 
            format: 'yyyy-mm-dd',   
            onSelect: function (selectedDate) { 
                  date = $('#start_date').datepicker('getDate');  
                  if (date) {     
                        date.setDate(date.getDate());      
                  }  
                  //console.log(date); 
                  $('#start_date').datepicker('option', 'minDate', date || 0);
                  //$("#form-supplier").valid();  
            }
      });
});


/************* add method validate *****************/

$.validator.addMethod("greaterThan", 
function(value, element, params) {
    if (!/Invalid|NaN/.test(new Date(value))) {
        return new Date(value) > new Date($(params).val());
    }   
    return new Date(value) > new Date($(params).val());   
},'Must be greater than {0}.');    

$.validator.addMethod("sirealRegex", function(value, element) {
    return this.optional(element) || /^[a-z0-9\-]+$/i.test(value);
}, 'Sireal number format not valid');   
 
$.validator.addMethod("phoneNumber", function (phone_number, element) {
        phone_number = phone_number.replace(/\s+/g, "");  
        return true;//this.optional(element) || phone_number.length > 9 && phone_number.match(/^(\+?1-?)?(\([2-9]\d{2}\)|[2-9]\d{2})-?[2-9]\d{2}-?\d{5}$/);  
}, "Please enter a valid phone number");       



/************* validate form supplier*****************/

$("#contract").validate({    
    rules: { 
        'contract[total_price]':"required", 
        'contract[start_date]':{
            required:true
        }, 
        'contract[end_date]':{ 
            required:true,
            greaterThan: "#start_date"              
        },
        'contract[serial_number]':{
            required: true, 
            sirealRegex: true,
        },
        'contract[contract_email]': { 
          required: true,
          email: true  
        },
        'contract[contract_name]':"required", 
        'contract[contract_company]':"required",
        'contract[contract_phone]':{
            required: true, 
            phoneNumber: true, 
        }, 
    },
    messages: {
        'contract[contract_name]':'Please enter full name.',
        'contract[total_price]':'Please enter price.',  
        'contract[contract_company]':'Please enter company name.', 
        'contract[start_date]':'Please enter work start date.', 
        'contract[end_date]':  
        { 
            required:'Please enter work end date.', 
            greaterThan:'Work start date and end date should be proper.'
        },
        'contract[contract_phone]': { 
            required: 'You must enter a sireal number.',   
            sirealRegex: 'Sireal number format not valid.'
        }, 
        'contract[contract_email]': {   
          required: 'We need your email address to contact you.',
          email: 'Your email address must be in the format of name@domain.com'
        },    
    }, 
    onfocusout: false,
    invalidHandler: function(form, validator) {
        var errors = validator.numberOfInvalids();
        if (errors) {                    
            validator.errorList[0].element.focus(); 
        }
    }, 
    submitHandler: function(form) {
      form.submit();
    }  
});
 
$('#contract_phone').keyup(function(){ 
    $(this).valid();    
});
</script> 