<div class="panel panel-default">
    <div class="panel-heading">  
        New User
        <a href="<?php echo $this->url('index').'admin/users/';?>" class="btn btn-success btn-xs pull-right"><i class="fa fa-undo" aria-hidden="true"></i>Back</a>
    </div>
    <div class="panel-body"> 
        <form action="<?php echo $this->url('index').'admin/users/?task=add';?>" enctype="multipart/form-data" name="registration" id="registration" method="post">
        	<div class="box-body">
            	<div class="form-group">
                  	<label>Level</label>
                  	<select class="form-control" name="user[type]">
                    	<option value="1" selected>User</option>
                        <option value="2">Supplier</option> 
                    </select>
                </div> 
                <div class="form-group">   
                  	<label>Gender</label>   
                  	<select class="form-control" name="user[gender]">
                    	<option value="1">Male</option>  
                        <option value="2">Female</option>     
                        <option value="0" selected>Other</option>  
                    </select>
                </div>
        		<div class="form-group">
          			<label for="exampleInputEmail1">Name</label>
          			<input type="text" class="form-control" id="name" name="user[name]" placeholder="Name">
        		</div>
                <div class="form-group"> 
          			<label for="exampleInputEmail1">Email</label> 
          			<input type="email" class="form-control" id="email" name="user[email]" placeholder="Email">
        		</div> 
                <div class="form-group">
          			<label for="exampleInputEmail1">Password</label>
          			<input type="password" class="form-control" id="password" name="user[password]" placeholder="Password">
        		</div>  
                <div class="form-group">
          			<label for="exampleInputEmail1">Phone</label>
          			<input type="text" class="form-control" id="phone" name="user[phone]" placeholder="Phone"> 
        		</div>
        		<div class="form-group">
          			<label for="birth_day">Birth Day</label>  
          			<input type="text" class="form-control datepicker" id="birth_day" name="user[birth_day]" placeholder="Birth Day" value="<?=date("Y-m-d");?>" readonly>
        		</div>
        		
        		<div class="form-group">
          			<label for="address">Address</label> 
          			<textarea rows="4" class="form-control" id="address" name="user[address]" placeholder="Address"></textarea>
        		</div>
        		<div class="form-group">
          			<label for="exampleInputFile">Image size:200x200px</label> 
          			<input type="file" id="pic" name="pic" onchange="imagePreview(this,'img-preview', 100)">
        			<div id="img-preview"></div>    
        		</div> 
                <div class="form-group"> 
                    <label for="active">Status</label><br> 
          			<input type="checkbox" name="active" id="active" value="0">     
        		</div>    
      		</div><!-- /.box-body -->
            <hr />
      		<div class="box-footer">
        		<button type="submit" class="btn btn-primary">Submit</button>
      		</div>
    	</form> 
    </div> 
</div>
<script type="text/javascript">
var url = "<?=$this->url('index').'admin/users/?task=checkEmail';?>";  
$(function() {
  $("form[name='registration']").validate({ 
    rules: { 
     'user[name]': {   
        required: true,
        minlength: 1 
     }, 
     'pic': "required",
     'user[email]':{  
        required: true, 
        email: true, 
        remote: 
        { 
            url: url,
            type: "post",  
            data:{
               'email':function()  
                {
                    return $('#email').val(); 
                }
           },  
           complete: function(data)  
            {
                console.log(data);
            }
        }
      },  
      'user[password]': { 
        required: true,
        minlength: 5
      } 
    }, 
    messages: { 
      'user[name]': "Please enter your name",  
      'user[password]': {  
        required: "Please provide a password",
        minlength: "Your password must be at least 5 characters long"
      },
      'user[email]': {  
        required: "Please enter a valid email address.",   
        remote: function() { return $.validator.format("This email is not available.", $("#email").val()) } 
      },        
      'pic': "Please enter image profile" 
    },
    submitHandler: function(form) { 
      form.submit();
    }
  });
});
</script>