<?php include('header.phtml'); ?>
<!-- /.parallax full screen background image --> 
<div class="home-img" style="background-image:url('<?=$this->url('index');?>backyard/images/bg_home.jpg');" data-img-width="2000" data-img-height="1333" data-diff="100">
	<?php include('menu.phtml'); ?>
</div>
 
<div id="content"> 
<div class="container" style="text-align:center">
	<h3>Connection ou enregistrement</h3>
</div>
    <div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="#" class="active" id="login-form-link">Login</a>
							</div>
							<div class="col-xs-6">
								<a href="#" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div> 
					<div class="panel-body"> 
						<div class="row">
							<div class="col-lg-12"> 
								<div id="login-rs"></div>
								<form id="login-form" action="" method="post" role="form" style="display: block;">
									<div class="form-group">
										<input type="email" name="email" id="login-email" tabindex="1" class="form-control" placeholder="Email" oninvalid="this.setCustomValidity('Please enter valid email')" required="tre">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="login-password" tabindex="2" class="form-control" placeholder="Password" oninvalid="this.setCustomValidity('Please enter password')" required="true">
									</div>
									<div class="form-group">
										<div class="row"> 
											<div class="col-sm-12"> 
												<button type="button" name="login-submit" onclick="goLogin();" id="login-submit" tabindex="4" class="btn btn-login btn-loader">Log In</button> 
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
													<a href="<?= $this->url('index').$lang.'/forgotpass'; ?>" tabindex="5" class="forgot-password">Forgot Password?</a>
												</div>
											</div>
										</div>
									</div>
								</form>    
								<div id="register-rs"></div> 
								<form id="register-form" action="" method="post" role="form" style="display: none;"> 
									<div class="form-group">
										<input type="text" name="name" id="regis-name" tabindex="1" class="form-control" placeholder="Name" required="true">
									</div>
									<div class="form-group">
										<input type="email" name="email" id="regis-email" tabindex="1" class="form-control" placeholder="Email Address" required="true">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="input-password" tabindex="2" class="form-control" placeholder="Password"  required="true">
									</div>
									<div class="form-group">
										<input type="password" name="confirm-password" id="input-confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password" required="true">
									</div>
									<div class="form-group">   
										<div class="row">
											<div class="col-sm-12"> 
												<button type="button" onclick="userRegister();" name="register-submit" id="register-submit" tabindex="4" class="btn btn-register btn-loader">Register Now</button> 
											</div>
										</div>
									</div>
								</form> 
								<hr> 
								<div class="row"> 
									<div class="col-sm-12">
										<a class="btn btn-block btn-social btn-facebook btn-lg" href="javascript:loginFB();">
									    	<span class="fa fa-facebook"></span> Sign in with facebook
									  	</a>
									</div> 
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php
include('footer.phtml');    
?>