<div id="app" class="home-img">  
<?php  
  include("header.phtml"); 
  include('menu.phtml');
?>
    <div class="content">    
        <section class="blogs" id="register">
            <div class="container"> 
            	<div class="row">  
            		<div class="col-md-9"> 
            			<h3><?=$this->translate('Blog'); ?></h3>  
            			<?php    
            			foreach ($blog->items as $key=>$items) {   
            			?>
            			  <div class="row">
                      <div class="col-md-12">  
                        <div class="row">
                          <div class="col-md-4">  
                            <a href="<?=$this->url('index').$lang.'/blogdetail/'.$items->id.'-'.strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $items->name))).'/';?>" class="thumbnail">        
                                <img src="<?=$urlFile.'/blog/'.$items->img;?>" class="img-responsive" alt="<?=$items->name;?>">     
                            </a> 
                          </div>
                          <div class="col-md-8">  
                            <div class="row">
                              <div class="col-md-12">
                                <h4><strong><a href="<?=$this->url('index').$lang.'/blogdetail/'.$items->id.'-'.strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $items->name))).'/';?>"><?=$items->name;?></a></strong></h4>
                              </div>
                            </div> 
                            <div class="row">
                              <div class="col-md-12">
                                <p></p> 
                                <p> 
                                    <i class="fa fa-calendar" aria-hidden="true"></i> <?=date("d F Y", strtotime($items->last_update));?>    
                                  | <i class="fa fa-eye" aria-hidden="true"></i> <?=number_format($items->view);?> <?=($items->view<=1)?$this->translate('View'):$this->translate('Views');?> 
                                </p>
                              </div>   
                            </div>        
                            <p><?=$items->detail_short;?></p> 
                            <p><a class="btn btn-primary" href="<?=$this->url('index').$lang.'/blogdetail/'.$items->id.'-'.strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $items->name))).'/';?>"><?=$this->translate('Read more'); ?></a></p>   
                          </div>
                        </div>  
                      </div>
                    </div> 
                    <hr> 
            			<?php 
            			} 
            			?>
            			<div class="row">
                    <div class="col-sm-12 text-center"> 
                        <?php  
                        if(!empty($pagination)) print_r($pagination);     
                        ?>
                    </div>
                  </div>
            			
            		</div> 
            		
            		<div class="col-md-3">  
            			
            			<div class="widget categories">
                    <h3><?=$this->translate('Hot'); ?></h3> 
                    <div class="row">
                      <div class="col-sm-12"> 
                        <?php 
                        ///print_r($recomment);
                        if($recomment->total>=1){ 
                          shuffle($recomment->items);  
                  			  foreach ($recomment->items as $key=>$items) {         
                  			?> 
                        <div class="single_comments">    
                          <a href="<?=$this->url('index').$lang.'/blogdetail/'.$items->id.'-'.strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $items->name))).'/';?>" >     
                            <img src="<?=$urlFile.'/blog/'.$items->img;?>" class="img-responsive" alt="<?=$items->name;?>"> 
                            <p><?=$items->name;?></p>    
                            <div class="entry-meta small muted"> 
                                <span><i class="fa fa-calendar" aria-hidden="true"></i> <a href="<?=$this->url('index').$lang.'/blogdetail/'.$items->id.'-'.strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $items->name))).'/';?>"><?=date("d F Y", strtotime($items->last_update));?></a></span>
                            </div>
                          </a> 
                        </div>
                        <?php   
                  			  }    
                        }  
                        ?>
                      </div>
                    </div>                     
                  </div> 
                    
                   
                  <div class="widget categories">
                    <h3><?=$this->translate('Fan Page'); ?></h3>   
                    <div class="row">
                      <div class="col-sm-12">  
                      
                        <div class="fb-page" data-href="https://www.facebook.com/heresclips/" data-tabs="timeline" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/heresclips/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/heresclips/">คลิปโดนๆ คลิปเฮียๆ</a></blockquote></div>
                      
                      </div>
                    </div>
                  </div>
                  
                  
                  
                  
            		</div>
            	</div>
            </div> 
        </section> 
        <!-- end regis -->  
    </div>
    
    <?php 
    include("footer.phtml");  
    ?> 
    
</div>
