<?php include('header.phtml'); ?>
<!-- /.parallax full screen background image --> 
<div class="fullscreen landing parallax" style="background-image:url('<?=$this->url('index');?>backyard/images/bg_home.jpg');" data-img-width="2000" data-img-height="1333" data-diff="100">
    <?php include('menu.phtml'); ?>
</div>
 
<div id="content"> 
    <div class="container">
    	<div class="row">
    	    <article class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">   
                <div id="wid-id-0"> 
                    <!-- widget div-->  
                    <div role="content"> 
                        <!-- widget content -->
                        <div class="widget-body">
        
                            <div class="row">  
                                <div id="bootstrap-wizard-1" class="col-md-12">    
                                	
                                    <div class="form-bootstrapWizard"> 
                                        <ul class="bootstrapWizard form-wizard contract-info-page"> 
                                            <li class="process-active active" id="tab-step1" data-target="#step1">  
                                                <a href="#tab1"  data-toggle="tab" class="active"> <span class="step">1</span> <span class="wizard-title">Login and contact details</span> </a>
                                            </li>   
                                            <li <?=($contract->status==6 || $contract->status==5)?'class="process-active active"':''?> data-target="#step2" id="tab-step2" class="">       
                                                <a href="#tab2" data-toggle="tab"> <span class="step">2</span> <span class="wizard-title disabled">Payment Details</span> </a>  
                                            </li>      
                                            <li <?=($contract->status==5)?'class="process-active active"':''?> data-target="#step3" id="tab-step3" class="">    
                                                <a href="#tab3" data-toggle="tab"> <span class="step">3</span> <span class="wizard-title disabled">Contract complete</span> </a>
                                            </li>  
                                        </ul>  
                                        <div class="clearfix"></div>  
                                    </div> 
                                     
                                    
                                    <div class="tab-content">  
                                        
                                        <div class="tab-pane <?=($contract->status==0)?'active':''?>" id="tab1">  
                                            
                                            <div class="tab-content-body">    
                                                <div class="row">
                                                    <div class="col-sm-12"> 
                                                    	
                                                    	<hr>
                                    					<br>
                                                    	 
                                                        <div class="content-body"> 
                                                            <?php  
                                                        	$request = $contract->request;
                                                        	$user_request = 0;
                                                        	if($request==1){
                                                        	    $user_id = $contract->buyer_id;
                                                        	}else{  
                                                        	    $user_id = $contract->seller_id;
                                                        	} 
                                                        	
                                                        	if($uid==$contract->seller_id){
                                                        	    $user_request = 1;   
                                                        	}  
                                                        	//echo $user_request;  
                                                        	?>
                                                        	<input type="hidden" name="pay_price" id="pay_price" value="<?=!empty($contract->pay_price)?$contract->pay_price:'';?>" />
                                                        	<input type="hidden" name="mangopay_id" id="mangopay_id" value="<?=!empty($userProfile->mangopay_id)?$userProfile->mangopay_id:'';?>" />
                                                        	<input type="hidden" name="mangopay_wallet" id="mangopay_wallet" value="<?=!empty($userProfile->mangopay_wallet)?$userProfile->mangopay_wallet:'';?>" />
                                                            <input type="hidden" name="user_request" id="user_request" value="<?=$user_request?>" /> 
                                                            <input type="hidden" class="form-control" id="login-email" placeholder="<?=$this->translate('Email address');?>" value="<?=!empty($userProfile->email)?$userProfile->email:'-';?>" required>
                                                        	
                                                        	<?php
                                                        	if(empty($uid)){
                                                        	?>
                                                        	<h3 class="text-center"><strong>Login to your zenovly.com account with "<?=!empty($userProfile->email)?$userProfile->email:'-';?>" and agree to this transaction</strong></h3>
                                                        	<br>
                                                            <div class="row"> 
	                                                        	<div class="col-md-4 col-md-offset-4">
		                                                        	<div id="login-rs"></div>  
								            						<fieldset>   
								            						    <?php     
								            						    //echo $userProfile->status; 
								            						    if($userProfile->status!='Active'){    
								            							?>
								            							    <div class="form-group input-group">   
    								            								<span class="input-group-addon"><i class="fa fa-key" aria-hidden="true"></i></span>    
    								            								<input id="login-password" name="login-password" type="password" placeholder="<?=$this->translate('Password'); ?>" class="form-control input-md" required="">
    								            							</div>  
    								            							<button type="button" onclick="customerNewpassword();" class="btn btn-lg btn-success btn-block btn-register btn-loader"> 
    								            								<i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->translate('Sign in');?>   
    								            							</button>   
								            							<?php
								            						    }else if(empty($uid)){  
								            							?>
								            							    <div class="form-group input-group">
    								            								<span class="input-group-addon"><i class="fa fa-key" aria-hidden="true"></i></span>  
    								            								<input type="password" id="login-password" placeholder="<?=$this->translate('Password');?>" class="form-control input-md" required="">
    								            							</div>  
    								            							<button type="button" onclick="goLogin();" class="btn btn-lg btn-success btn-block btn-register btn-loader"> 
    								            								<i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->translate('Sign in');?>  
    								            							</button>
								            							<?php
								            						    }
								            							?>
								            							
								            						</fieldset>
	                                                        	</div>
	                                                        </div> 
	                                                        <hr> 
	                                                        <?php
                                                        	} 
	                                                        ?>
	                                                        <div class="row">   
	                                                        	<div class="col-md-12">      
                                                                    <h4><strong>Project details</strong></h4>      
                                                                    <br>      
                                                                    <input type="hidden" id="contract_id" name="contract_id" value="<?=$contract->id;?>"/> 
                                                                    <input type="hidden" id="buyer_id" name="buyer_id" value="<?=$contract->buyer_id;?>"/> 
                                                                    <input type="hidden" id="seller_id" name="contract_id" value="<?=$contract->seller_id;?>"/>
                                                                    
                                                                    <table class="table table-bordered table-responsive">  
                                                                      <thead> 
                                                                        <tr>  
                                                                          <th align="center">Project name</th>  
                                                                          <th align="center">Start date</th> 
                                                                          <th align="center">End date</th>  
                                                                          <th align="right" class="align-right">Price</th>
                                                                        </tr>
                                                                      </thead>   
                                                                       
                                                                      <tbody> 
                                                                        <tr>
                                                                          <td id="detail-projectname"><?=!empty($contract->project_name)?$contract->project_name:'-';?></td>
                                                                          <td id="detail-start-date"><?=!empty($contract->start_date)?date("m/d/Y", strtotime($contract->start_date)):'-';?></td>
                                                                          <td id="detail-end-date"><?=!empty($contract->end_date)?date("m/d/Y", strtotime($contract->end_date)):'-';?></td>
                                                                          <td id="detail-sub-price" class="align-right"><?=!empty($contract->total_price)?number_format($contract->total_price,2):'-';?></td> 
                                                                        </tr> 
                                                                        <tr>    
                                                                          <td colspan="3" class="align-right"><b>Transfer price</b></td>       
                                                                          <td id="detail-total-price" class="align-right"><?=!empty($contract->transfer_price)?number_format($contract->transfer_price,2):'-';?></td>   
                                                                        </tr>
                                                                        <tr>    
                                                                          <td colspan="3" class="align-right"><b>Pay price</b></td>      
                                                                          <td id="detail-total-price" class="align-right"><?=!empty($contract->pay_price)?number_format($contract->pay_price,2):'-';?></td>  
                                                                        </tr>
                                                                      </tbody>  
                                                                    </table>  
                                                                    <div class="row"> 
                                                                        <div class="col-md-6">
                                                                            <h4><strong>Buyer information</strong></h4> 
                                                                            <br> 
                                                                            <div class="form-group">  
                                                                                <label>Name</label> 
                                                                                <p><?=!empty($contract->buyer_name)?$contract->buyer_name:'-';?></p>   
                                                                            </div>
                                                                            <div class="form-group">  
                                                                                <label>Email</label>  
                                                                                <p><?=!empty($contract->buyer_email)?$contract->buyer_email:'-';?></p>   
                                                                            </div>
                                                                            <div class="form-group">  
                                                                                <label>Phone Number</label>  
                                                                                <p><?=!empty($contract->buyer_number)?$contract->buyer_number:'-';?></p>   
                                                                            </div>
                                                                        </div> 
                                                                        <div class="col-md-6">
                                                                            <h4><strong>Seller information</strong></h4>
                                                                            <br>
                                                                            <div class="form-group">  
                                                                                <label>Name</label> 
                                                                                <p><?=!empty($contract->seller_name)?$contract->seller_name:'-';?></p>   
                                                                            </div> 
                                                                            <div class="form-group">  
                                                                                <label>Email</label>  
                                                                                <p><?=!empty($contract->seller_email)?$contract->seller_email:'-';?></p>   
                                                                            </div>
                                                                            <div class="form-group">  
                                                                                <label>Phone Number</label>  
                                                                                <p><?=!empty($contract->seller_number)?$contract->seller_number:'-';?></p>   
                                                                            </div>
                                                                        </div>
                                                                    </div> 
                                                                    <?php
                                                                    if(!empty($contract->contract_number) && 0){ 
                                                                    ?>
                                                                    <hr>  
                                                                    <h4><strong>Contract No.</strong></h4>     
                                                                    <p><?=$contract->contract_number;?></p>
                                                                    <?php
                                                                    }
                                                                    ?>
                                                                    <hr>  
                                                                    <h4><strong>Who will pay the Free</strong></h4>
                                                                    <?php
                                                                    $who_pay_fee = 'Buyer'; 
                                                                    if($contract->who_pay_fee==1){
                                                                        $who_pay_fee = 'Seller';    
                                                                    }else if($contract->who_pay_fee==2){
                                                                        $who_pay_fee = ' 50% 50%';      
                                                                    }  
                                                                    ?> 
                                                                    <p><?=$who_pay_fee;?></p>  
                                                                    <hr>   
                                                                    <h4><strong>Detail : Note</strong></h4>    
                                                                    <p><?=!empty($contract->note)?$contract->note:'-';?></p>
                                                                    <?php   
                                                                	$chk_user = false;      
                                                                	if($contract->seller_id==$uid || $contract->buyer_id==$uid){  
                                                                	    $chk_user = true; 
                                                                	}  
								                                	if($chk_user){            
								                                	?> 
                                                                    <div class="contact-result"></div> 
                                                                    <div class="txt-policy"> 
                                                                        <p>xxx xxx According to the total price, the duration of the contract different contracts can be issued automatically. 
                                    The element will include customer information and supplier information dynamically  xxx                                                                            <br>1. xxxx xxxx                                                                            <br>2.xxxx xxxx                                                                            <br>3.xxxx xxxx                                                                            <br>4.xxxx xxxx                                                                            <br>5.xxxx xxxx                                                                            <br>6.xxxx xxxx                                                                            <br>7.xxxx xxxx 
                                                                        </p>  
                                                                    </div>   
                                                                    
                                                                    <div class="form-group new-form-group">  
                                    									<div class="checkbox">  
                                											 <label> 
                                											     <input type="checkbox" id="check_policy" name="check_policy" class="check_policy">I have read and understand the privacy policy.  
                                											 </label>
                                										</div> 
                                										<div id="error-policy"></div> 
                                    								</div>
                                    								<?php
								                                	} 
                                    								?>
                                                                </div>
	                                                        </div> 
                                                        </div>
                                                        <hr/> 
                                                        <div class="form-actions">  
                                                        
                                                            <div class="row">  
                                                                <div class="col-md-12">
                                                                    <ul class="pager wizard no-margin">
                                                                    	<?php 
									                                	if($chk_user && $contract->status!=6){                  
									                                	?> 
                                                                        <li class="next">  
                                                                            <a href="javascript:void(0);"  onclick="$('#payment-loading').show();"   id="btn-next-step1" class="btn btn-lg txt-color-darken btn-boy btn-loader"> Next </a>     
                                                                        </li>
                                                                        <?php 
									                                	}  
                                                                        ?>
                                                                    </ul>
                                                                </div>
                                                            </div> 
                                                        </div>   
                                                    </div>  
                                                </div> 
                                            </div> 
                                        </div>  
                                          
                                        <div class="tab-pane <?=($contract->status==6)?'active':''?>" id="tab2">  
                                            <div class="tab-content-body">
                                            	<hr> 
                            					<br> 
                                            	<div class="content-body"> 
                                            	    <?php
                                                	if(empty($uid)){ 
                                                	?>
                                                	<h3 class="text-center"><strong>Login to your zenovly.com account with "<?=!empty($userProfile->email)?$userProfile->email:'-';?>" and agree to this transaction</strong></h3>
                                                	<br>
                                            	    <div class="row"> 
                                                    	<div class="col-md-4 col-md-offset-4">
                                                        	<div id="login-rs"></div>  
						            						<fieldset>   
						            						    <?php     
						            						    //echo $userProfile->status; 
						            						    if($userProfile->status!='Active'){    
						            							?>
						            							    <div class="form-group input-group">   
							            								<span class="input-group-addon"><i class="fa fa-key" aria-hidden="true"></i></span>    
							            								<input id="login-password" name="login-password" type="password" placeholder="<?=$this->translate('Password'); ?>" class="form-control input-md" required="">
							            							</div>  
							            							<button type="button" onclick="customerNewpassword();" class="btn btn-lg btn-success btn-block btn-register btn-loader"> 
							            								<i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->translate('Sign in');?>   
							            							</button>   
						            							<?php
						            						    }else if(empty($uid)){  
						            							?>
						            							    <div class="form-group input-group">
							            								<span class="input-group-addon"><i class="fa fa-key" aria-hidden="true"></i></span>  
							            								<input type="password" id="login-password" placeholder="<?=$this->translate('Password');?>" class="form-control input-md" required="">
							            							</div>  
							            							<button type="button" onclick="goLogin();" class="btn btn-lg btn-success btn-block btn-register btn-loader"> 
							            								<i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->translate('Sign in');?>  
							            							</button>
						            							<?php
						            						    }
						            							?>
						            							
						            						</fieldset>
                                                    	</div>
                                                    </div> 
                                                    <hr> 
                                                    <?php
                                                	} 
                                                    ?>
                                                    <div class="row">   
                                                    	<div class="col-md-12">      
                                                            <h4><strong>Project details</strong></h4>      
                                                            <br>      
                                                            <input type="hidden" id="contract_id" name="contract_id" value="<?=$contract->id;?>"/> 
                                                            <input type="hidden" id="buyer_id" name="buyer_id" value="<?=$contract->buyer_id;?>"/> 
                                                            <input type="hidden" id="seller_id" name="contract_id" value="<?=$contract->seller_id;?>"/>
                                                            
                                                            <table class="table table-bordered table-responsive">  
                                                              <thead> 
                                                                <tr>  
                                                                  <th align="center">Project name</th>  
                                                                  <th align="center">Start date</th> 
                                                                  <th align="center">End date</th>  
                                                                  <th align="right" class="align-right">Price</th>
                                                                </tr>
                                                              </thead>   
                                                               
                                                              <tbody> 
                                                                <tr>
                                                                  <td id="detail-projectname"><?=!empty($contract->project_name)?$contract->project_name:'-';?></td>
                                                                  <td id="detail-start-date"><?=!empty($contract->start_date)?date("m/d/Y", strtotime($contract->start_date)):'-';?></td>
                                                                  <td id="detail-end-date"><?=!empty($contract->end_date)?date("m/d/Y", strtotime($contract->end_date)):'-';?></td>
                                                                  <td id="detail-sub-price" class="align-right"><?=!empty($contract->total_price)?number_format($contract->total_price,2):'-';?></td> 
                                                                </tr> 
                                                                <tr>    
                                                                  <td colspan="3" class="align-right"><b>Transfer price</b></td>       
                                                                  <td id="detail-total-price" class="align-right"><?=!empty($contract->transfer_price)?number_format($contract->transfer_price,2):'-';?></td>   
                                                                </tr>
                                                                <tr>    
                                                                  <td colspan="3" class="align-right"><b>Pay price</b></td>      
                                                                  <td id="detail-total-price" class="align-right"><?=!empty($contract->pay_price)?number_format($contract->pay_price,2):'-';?></td>  
                                                                </tr>
                                                              </tbody>  
                                                            </table>   
                                                            <div class="row"> 
                                                                <div class="col-md-6">
                                                                    <h4><strong>Buyer information</strong></h4> 
                                                                    <br> 
                                                                    <div class="form-group">  
                                                                        <label>Name</label> 
                                                                        <p><?=!empty($contract->buyer_name)?$contract->buyer_name:'-';?></p>   
                                                                    </div>
                                                                    <div class="form-group">  
                                                                        <label>Email</label>  
                                                                        <p><?=!empty($contract->buyer_email)?$contract->buyer_email:'-';?></p>   
                                                                    </div>
                                                                    <div class="form-group">  
                                                                        <label>Phone Number</label>  
                                                                        <p><?=!empty($contract->buyer_number)?$contract->buyer_number:'-';?></p>   
                                                                    </div>
                                                                </div> 
                                                                <div class="col-md-6">
                                                                    <h4><strong>Seller information</strong></h4>
                                                                    <br>
                                                                    <div class="form-group">  
                                                                        <label>Name</label> 
                                                                        <p><?=!empty($contract->seller_name)?$contract->seller_name:'-';?></p>   
                                                                    </div> 
                                                                    <div class="form-group">  
                                                                        <label>Email</label>  
                                                                        <p><?=!empty($contract->seller_email)?$contract->seller_email:'-';?></p>   
                                                                    </div>
                                                                    <div class="form-group">  
                                                                        <label>Phone Number</label>  
                                                                        <p><?=!empty($contract->seller_number)?$contract->seller_number:'-';?></p>   
                                                                    </div>
                                                                </div>
                                                            </div> 
                                                            <?php
                                                            if(!empty($contract->contract_number) && 0){ 
                                                            ?>
                                                            <hr>  
                                                            <h4><strong>Contract No.</strong></h4>     
                                                            <p><?=$contract->contract_number;?></p>
                                                            <?php
                                                            }
                                                            ?>
                                                            <hr>  
                                                            <h4><strong>Who will pay the Free</strong></h4>
                                                            <?php
                                                            $who_pay_fee = 'Buyer'; 
                                                            if($contract->who_pay_fee==1){
                                                                $who_pay_fee = 'Seller';    
                                                            }else if($contract->who_pay_fee==2){
                                                                $who_pay_fee = ' 50% 50%';      
                                                            }  
                                                            ?> 
                                                            <p><?=$who_pay_fee;?></p>  
                                                            <hr>   
                                                            <h4><strong>Detail : Note</strong></h4>    
                                                            <p><?=!empty($contract->note)?$contract->note:'-';?></p>
                                                        </div>
                                                    </div>
	                                        		<div class="row">     
	                                                	<div class="col-md-6 col-md-offset-3"> 
	                                                	    <br><br>  
	                                                	    <a  onclick="$('#payment-loading').show();"  href="<?=$Api_url.'/pay/'.$userProfile->mangopay_id.'/?username='.$Api_username.'&password='.$Api_password.'&wid='.$userProfile->mangopay_wallet.'&amount='.($contract->pay_price*100).'&zenovly_id='.$contract->id.'&returnURL='.$full_url;?>" class="btn btn-success btn-lg btn-block">Go To Payment</a> 
												        </div>      
	                                                </div>
	                                            </div>
	                                            
                                        	</div> 
                                        </div>      
                                        
                                        
                                        <div class="tab-pane <?=($contract->status==5)?'active':''?>" id="tab3">    
                                            <div class="tab-content-body">
                                            	<hr>
                            					<br>  
                                                <div class="content-body"> 
	                                        		<div class="row">    
	                                        			<div class="col-md-12">   
									            		     <div class="mission-block text-center contract-complete"> 
									            		          <div class="icon-send-block step-complete"> 
									            		              <i class="fa fa-check-circle-o" aria-hidden="true"></i> 
									            		          </div>   
									            		          <h1>Contract complete</h1>          
									            		          <p>xxxxx xxxxx  xxxx xxxxx xxxxx</p>     
									            		          <a href="<?=$this->url('index').$lang.'/'; ?>contractinfo/<?=$contract->id;?>/"  class="btn btn-primary btn-manage-mission btn-loader">Go to Contract</a>
									            		     </div> 
									            		 </div>
	                                                </div>
	                                            </div>
                                        	</div>
                                        </div>
                                        
                                    </div>
                                </div> 
                            </div> 
                        </div>
                        <!-- end widget content -->
                    </div>
                    <!-- end widget div -->
                </div>
                <!-- end widget -->
            </article>	            
    	
    	</div>
    </div>
</div> 
<div class="payment-loading" id="payment-loading"> 
    <div class="txt-loading">
        <p>“ you will be redirected to a secure payment page MangoPay”</p>
        <div class="block-loader"></div> 
    </div>
</div>
 
<?php 
include('footer.phtml');   
?>