<?php include('header.phtml'); ?>
<!-- /.parallax full screen background image --> 
<div class="fullscreen landing parallax" style="background-image:url('<?=$this->url('index');?>backyard/images/bg_home.jpg');" data-img-width="2000" data-img-height="1333" data-diff="100">
    <?php include('menu.phtml'); ?>
</div>  
<div class="content">     
    <section class="fogotpass" id="fogotpass">
        <div class="container"> 
        	<div class="row">  
        		<div class="col-md-6 col-md-offset-3"> 
        			<div class="panel panel-info">  
        				<div class="panel-heading">
        					<h3 class="panel-title"><i class="fa fa-key" aria-hidden="true"></i> <?=$this->translate('Forget the password ?');?></h3>  
        				</div>
        				<div class="panel-body">
        				    <div id="forgot-email-result"></div>  
                            <div class="form-group">   
                    			 <label class="control-label" for="login-email"><?=$this->translate('Email address');?></label>   
                    			 <input type="email" class="form-control" id="forgot-email" name="forgot-email" placeholder="<?=$this->translate('Email address');?>"> 
                    		</div>
                    		<hr> 
                    		<button type="button" onclick="forgotpassword();" class="btn btn-primary btn-block btn-forgotpassword btn-loader"><i class="fa fa-paper-plane-o" aria-hidden="true"></i> <?=$this->translate('Send'); ?></button>
        				</div>
        			</div>
        		</div>
        	</div>
        </div> 
    </section> 
    <!-- end regis -->  
</div>

<?php 
include("footer.phtml");  
?> 
    
