<?php  
if(!empty($this->SEO['title']))$title=$this->SEO['title'];
$this->headMeta()->appendName('keywords', !empty($this->SEO['keywords'])?$this->SEO['keywords']:'');
$this->headMeta()->appendName('description', !empty($this->SEO['description'])?$this->SEO['description']:'');
$this->headMeta()->setProperty('og:title', !empty($this->SEO['title'])?$this->SEO['title']:''); 
$this->headMeta()->setProperty('og:description', !empty($this->SEO['description'])?$this->SEO['description']:'');
$this->headMeta()->setProperty('og:url', !empty($this->SEO['url'])?$this->SEO['url']:$this->full_url);   
$this->headMeta()->setProperty('og:image', !empty($this->SEO['image'])?$this->SEO['image']:$this->url('index').'img/noimage.png'); 
$this->headMeta()->setProperty('og:image:type', 'image/jpeg'); 
$this->headMeta()->setProperty('og:image:width', '400 ');
$this->headMeta()->setProperty('og:image:height', '300');    
$this->headMeta()->setProperty('og:site_name', $this->translate('Site name')); 
$this->headMeta()->setProperty('og:locale', !empty($this->SEO['locale'])?$this->SEO['locale']:'fr_FR');     
$this->headMeta()->setProperty('og:type', 'website');   
$this->headMeta()->setProperty('fb:app_id', !empty($this->SEO['fb_app_id'])?$this->SEO['fb_app_id']:'128202497713838');
$this->headMeta()->appendName('twitter:title', !empty($this->SEO['title'])?$this->SEO['title']:'');  
$this->headMeta()->appendName('twitter:description', !empty($this->SEO['description'])?$this->SEO['description']:''); 
$this->headMeta()->appendName('twitter:image:src', !empty($this->SEO['image'])?$this->SEO['image']:$this->url('index').'img/noimage.png'); 
$this->headMeta()->appendName('twitter:card', 'summary');  
$this->headMeta()->appendName('twitter:site', $this->translate('Site name'));       
$this->headMeta()->appendName('twitter:creator', !empty($this->SEO['creator'])?$this->SEO['creator']:'@Zenovly');   
$this->headMeta()->appendName('twitter:domain', !empty($this->SEO['domain'])?$this->SEO['domain']:'zenovly.com'); 
$this->headTitle($title); 
 
?>
<script>
  <?php
  include('lang.phtml');   
  ?>
	var page = 1;
	var lang = '<?php echo $this->lang; ?>';
	var total = 0;
	var id = '<?php echo $this->id; ?>';
	var action = '<?php echo $this->action; ?>';
	var noCache = '<?php echo $this->nocache; ?>';
	var baseURL = '<?php echo $this->url('index'); ?>';
	var apiUrl = '<?php echo $this->Api_url; ?>';
	var user_api = 'username=<?php echo $this->Api_username; ?>';
	var password_api = 'password=<?php echo $this->Api_password; ?>';
	var uimg = '';  
</script>    
<div id="fb-root"></div> 
<!-- /.preloader --> 

<div id="top"></div>

<div id="preloader"></div>