<?php
echo " 
var txt_lang = {   
    'oops_somting': '".$this->translate('Oops! Something went wrong.')."', 
    'confirm_policy': '".$this->translate('Please confirm the privacy policy.')."',
    'alert_sireal': '".$this->translate('Sireal number must contain only letters, numbers, or dashes.')."',
    'alert_phone': '".$this->translate('Please enter a valid phone number')."',
    'alert_full_name': '".$this->translate('Please enter full name')."',
    'alert_image_type': '".$this->translate('Please enter a value with a valid mimetype (pdf,jpg,jpeg,png,gif).')."',
    'alert_price': '".$this->translate('Please enter price.')."',
    'alert_company': '".$this->translate('Please enter company name.')."',
    'alert_start_date': '".$this->translate('Please enter work start date.')."',
    'alert_end_date': '".$this->translate('Please enter work end date.')."',
    'alert_date_match': '".$this->translate('Work start date and end date should be proper.')."',
    'alert_enter_sireal': '".$this->translate('You must enter a sireal number')."',
    'alert_sireal_format': '".$this->translate('sireal number format not valid')."',
    'alert_email': '".$this->translate('We need your email address to contact you.')."',
    'alert_email_format': '".$this->translate('Your email address must be in the format of name@domain.com')."',
    'alert_confirm_logout': '".$this->translate('Press ok to logout!')."',
    'alert_valid_email': '".$this->translate('Please enter a valid email address.')."',
    'alert_password_long': '".$this->translate('Your password must be at least 5 characters long.')."',
    'alert_auth_failed': '".$this->translate('Authentication failed. Please login try again.')."',
    'alert_login_first': '".$this->translate('Please login first !.')."',
    'alert_confirm_password': '".$this->translate('Password does not match the confirm password')."',
    'alert_registered': '".$this->translate('You have been successfully registered. please you login.')."',
    'alert_profile_successfuly': '".$this->translate('Edit profile successfuly')."',
    'alert_new_password_long': '".$this->translate('Your new password must be at least 5 characters long.')."',
    'alert_password_successfuly': '".$this->translate('New password successfuly')."',
    'alert_upload_profile_successfully': '".$this->translate('Upload profile photo successfully')."', 
    'alert_terms_of_service': '".$this->translate('I agree to the Terms of Service.')."', 
    'alert_confirm_contract_successfuly': '".$this->translate('Confirm contract successfully.')."', 
    'alert_plese_subject': '".$this->translate('Please enter subject.')."',  
    'alert_plese_message': '".$this->translate('Please enter message.')."', 
    'alert_send_msg_successfuly': '".$this->translate('Your message has been sent. Thank you!')."',
    'connected_facebook': '".$this->translate('Connected Facebook')."', 
    'alert_connected_facebook_successfuly': '".$this->translate('Connect Facebook Successfuly.')."'
};
";  
?>