<div id="app" class="home-img">  
<?php  
  include("header.phtml"); 
  include('menu.phtml');
?>
    <div class="content">    
        <section class="blogs" id="register">
            <div class="container"> 
            	<div class="row">  
            		<div class="col-md-12"> 
            			<h3><?=$this->translate('What is Wezenit?'); ?></h3>
            			
            			<div class="column-7 w-col w-col-8 w-col-stack">
        <div class="div-block-8">
          <h2 data-ix="new-interaction-3" class="heading-2" style="opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px); transition: opacity 200ms, transform 462ms;">Avec Wezenit, vous pouvez acheter et vendre <span class="text-span-2">tout</span>, <span class="text-span-4">partout</span>, en toute sérénité</h2>
          <h2 data-ix="new-interaction-3" class="paragraph" style="opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px); transition: opacity 200ms, transform 462ms;">Wezenit est à vos cotés et fournit la confiance nécessaire à toutes vos transactions. Avec Wezenit fini les risques de non-paiement pour un vendeur/prestataire et les risques de non réalisation ou de disparition de son paiement pour un acheteur/client. Plus besoin de procédures longues et couteuses pour ne même pas se faire rembourser. <br>Avec Wezenit, plus aucune raison de ne pas se lancer puisqu’il n’y a pas de risques.</h2><a href="#wezenitdetails" data-ix="new-interaction-3" class="button-2 submit-button w-button" style="transition: all 3.5s ease 0s, opacity 200ms, transform 462ms; opacity: 1; transform: translateX(0px) translateY(0px) translateZ(0px);">Une transaction Zen en 5 étapes</a></div>
      </div>
            			
            		</div>
            	</div>
            </div>
        </section>
    </div>
<?php include("footer.phtml"); ?>
</div>
