<div id="app">  
    <?php  
    include("header.phtml"); 
    ?> 
    <div class="content">    
        <section class="blogs" id="register">
            <div class="container"> 
            	<div class="row">  
            		<div class="col-md-9"> 
            		  
            		  
                  
            		  <?php     
            		  //print_r($blogDetail);   
            			if(!empty($blogDetail)){        
            			?> 
              			<h3><?=$this->translate('Blog'); ?> : <?=$blogDetail->name;?></h3>  
              			
              			<div class="row">
                      <div class="col-sm-12 text-center">   
                        <img src="<?=$blogDetail->img;?>" class="img-responsive img-blog" /> 
                      </div> 
                    </div> 
                    
                    <hr class="hr-blog" />
                    
            			  <div class="row"> 
                      <div class="col-md-12">     
                         
                        <div class="row">
                          <div class="col-md-12">
                            <p></p> 
                            <p> 
                                <i class="fa fa-calendar" aria-hidden="true"></i> <?=date("d F Y", strtotime($blogDetail->last_update));?>         
                              | <i class="fa fa-eye" aria-hidden="true"></i> <?=number_format($blogDetail->view);?> <?=($blogDetail->view<=1)?'View':'Views';?>
                            </p>
                          </div>    
                        </div> 
                        
                        <?=$blogDetail->detail;?>    
                        
                      </div>
                    </div>
                    
                    <?php      
                    if(!empty($blogDetail->gallery)){       
              			  foreach ($blogDetail->gallery as $items) {         
              			?>
                      <div class="row gallery-list">   
                        <div class="col-sm-12 text-center">     
                          <img src="<?=$items;?>" class="img-responsive img-blog" /> 
                        </div>
                      </div>
                    <?php
              			  } 
              			} 
                    ?>
                    <br> 
                    <div class="row"> 
                      <div class="col-sm-12"> 
                        <h3><?=$this->translate('Tell your friends'); ?></h3>
                        <div id="shareButtonLabel"></div> 
                      </div>
                    </div>
                    <hr> 
            			<?php 
            			} 
            			?>
            			<div class="row">
                    <div class="col-sm-12 text-center"> 
                      <div class="fb-comments" data-href="<?=$full_url;?>" data-width="100%"  data-numposts="5"></div>   
                    </div>
                  </div>
            			
            		</div> 
            		
            		<div class="col-md-3">  
            			
            			<div class="widget categories">
                    <h3><?=$this->translate('Hot'); ?></h3>   
                    <div class="row">
                      <div class="col-sm-12"> 
                        <?php   
                        if($recomment->total>=1){ 
                          shuffle($recomment->items);   
                  			  foreach ($recomment->items as $key=>$items) {            
                  			?> 
                        <div class="single_comments">    
                          <a href="<?=$this->url('index').$lang.'/blogdetail/'.$items->id.'-'.strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $items->name))).'/';?>" >  
                            <img src="<?=$urlFile.'/blog/'.$items->img;?>" class="img-responsive" alt="<?=$items->name;?>"> 
                            <p><?=$items->name;?></p>   
                            <div class="entry-meta small muted">
                                <span><i class="fa fa-calendar" aria-hidden="true"></i> <a href="<?=$this->url('index').$lang.'/blogdetail/'.$items->id.'-'.strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $items->name))).'/';?>"><?=date("d F Y", strtotime($items->last_update));?></a></span>
                            </div>
                          </a> 
                        </div>
                        <?php     
                  			  }       
                        }  
                        ?>
                      </div>
                    </div>                     
                  </div> 
                    
                   
                  <div class="widget categories">
                    <h3><?=$this->translate('Fan Page'); ?></h3>  
                    <div class="row">
                      <div class="col-sm-12">  
                        
                        <div class="fb-page" data-href="https://www.facebook.com/heresclips/" data-tabs="timeline" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/heresclips/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/heresclips/">คลิปโดนๆ คลิปเฮียๆ</a></blockquote></div>
                      
                      </div>
                    </div>
                  </div>
                  
                  
                  
                  
            		</div>
            	</div>
            </div> 
        </section> 
        <!-- end regis -->  
    </div>
    
    <?php 
    include("footer.phtml");  
    ?> 
    
</div>
