<div id="app">  
    <?php  
    include("header.phtml"); 
    ?> 
    <div class="content">     
        <section class="register" id="register">
            <div class="container"> 
            	<div class="row"> 
            		<div class="col-md-6 col-md-offset-3"> 
            			<div class="panel panel-default">   
            				<div class="panel-heading">
            					<h3 class="panel-title"><i class="fa fa-key" aria-hidden="true"></i> <?=$this->translate('Forget the password ?');?></h3>  
            				</div>
            				<div class="panel-body">
            				    <?php   
            				    if(!empty($time_expire)){           
            				    ?>
            				    <div id="forgot-newpass-result"></div>  
            					<form id="forgot-form" name="forgot-form" action="" onsubmit="return false;" method="post">     
            						<fieldset>
            						    <input type="hidden" name="forgot-newemail" id="forgot-newemail" value="<?=$token_email;?>"/>   
            							<div class="form-group input-group">  
            								<span class="input-group-addon"><i class="fa fa-key" aria-hidden="true"></i></span>  
            								<input id="forgot-newpass" name="forgot-newpass" type="password" placeholder="<?=$this->translate('New Password'); ?>" class="form-control input-md" required="">
            							</div> 
            							<button  type="button" onclick="forgotnewpassword();"  class="btn btn-lg btn-success btn-block btn-forgot btn-loader"> 
            								<i class="fa fa-floppy-o" aria-hidden="true"></i> <?=$this->translate('Save'); ?>     
            							</button>
            						</fieldset>  
            					</form>
            					<?php 
            				    }else{    
            					?>
            					<div class="alert alert-danger text-center">
                                  <h1><?=$this->translate('forgot password has expired.'); ?></h1> 
                                </div>
                                <a href="<?=$this->url('index'); ?>"  class="btn btn-lg btn-danger btn-block btn-forgot btn-loader"><i class="fa fa-home" aria-hidden="true"></i> <?=$this->translate('Home'); ?></a>
            					<?php
            				    }
            					?>
            				</div>
            			</div>
            		</div>
            	</div>
            </div> 
        </section> 
        <!-- end regis -->  
    </div>
    
    <?php 
    include("footer.phtml"); 
    ?> 
    
</div>
