<div class="bg-info-right"> 
    <div class="header-blue"> 
        <div class="disc-rad star-disc"><i class="fa fa-star" aria-hidden="true"></i></div> 
        <h3><strong>Begin your 1st project!</strong></h3> 
        <p>EACH PROJECT BOOSTS YOUR REPUTATION ON HOPWORK.</p> <br>
        <h4>Win new clients and build your revenues.</h4>  
        <br>
    </div>
    <div class="help-info"> 
        <h3>Hopwork protect you</h3> 
        <br>
        <div class="row"> 
            <div class="col-sm-3">  
                <div class="white-sky-disc"><i class="fa fa-lock" aria-hidden="true"></i></div>    
            </div>
            <div class="col-sm-9"> 
                <h4>Your secure payments</h4> 
                <p>The client prepays the amount at the beginning of the project. Once they confirm completion, the funds are unfrozen and you are paid within 48h.</p>
            </div>
        </div>
        
        <div class="row">  
            <div class="col-sm-3">  
                <div class="white-sky-disc"> 
                    <i class="fa fa fa-check" aria-hidden="true"></i>    
                </div>     
            </div>
            <div class="col-sm-9"> 
                <h4>Your contracts made simple</h4> 
                <p>Follow the guide, and Hopwork will take care of the rest. Quotes, contracts and invoices 100% online.</p>
            </div>
        </div>
        
        <div class="row"> 
            <div class="col-sm-3">   
                <div class="white-sky-disc"><i class="fa fa-lock" aria-hidden="true"></i></div>    
            </div>
            <div class="col-sm-9">  
                <h4>Your projects insured by AXA for up to 9M€</h4> 
            </div>
        </div>
        
    </div>
</div> 