<div id="app">  
    <?php  
    include("header.phtml"); 
    ?>  
    
    <!---->
    <section id="cta-1"> 
        <div class="container">
            <div class="row">
                <div class="cta-info text-center">
                    <h3><?=$this->translate('Stay Zen during your renovation'); ?></h3> 
                </div>
            </div>
        </div> 
    </section> 
    <!---->
    
    <!---->
    <section id="feature" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-4 wow fadeInLeft delay-05s"> 
                    <div class="section-title">
                        <h2 class="head-title"><?=$this->translate('Features'); ?></h2> 
                        <hr class="botm-line">
                        <p class="sec-para"><?=$this->translate('Features Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..'); ?></p>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="col-md-6 wow fadeInRight delay-02s">
                        <div class="icon">
                            <i class="fa fa-paint-brush"></i>
                        </div>
                        <div class="icon-text">
                            <h3 class="txt-tl"><?=$this->translate('Vos travaux sans soucis 1'); ?></h3>
                            <p class="txt-para"><?=$this->translate('Vos 1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper.'); ?> </p>
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeInRight delay-02s">
                        <div class="icon">
                            <i class="fa fa-cogs"></i>
                        </div>
                        <div class="icon-text">
                            <h3 class="txt-tl"><?=$this->translate('Vos travaux sans soucis 2'); ?></h3>
                            <p class="txt-para"><?=$this->translate('Vos 2 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper.'); ?> </p>
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeInRight delay-04s">
                        <div class="icon">
                            <i class="fa fa-mobile"></i>
                        </div>
                        <div class="icon-text">
                            <h3 class="txt-tl"><?=$this->translate('Vos travaux sans soucis 3'); ?></h3>
                            <p class="txt-para"><?=$this->translate('Vos 3 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper.'); ?> </p>
                        </div>
                    </div>
                    <div class="col-md-6 wow fadeInRight delay-04s">
                        <div class="icon">
                            <i class="fa fa-desktop"></i> 
                        </div>
                        <div class="icon-text">
                            <h3 class="txt-tl"><?=$this->translate('Vos travaux sans soucis 4'); ?></h3>
                            <p class="txt-para"><?=$this->translate('Vos 4 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper.'); ?> </p>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </section>
    <!---->
    <section class="section-padding parallax bg-image-2 section wow fadeIn delay-08s" id="cta-2">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="cta-txt"> 
                        <h3><?=$this->translate('Subscribe'); ?></h3> 
                        <p><?=$this->translate('Subscribe Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper.'); ?> </p>
                    </div>
                </div> 
                <div class="col-md-4 text-center">  
                    <a href="javascript:void(0);" id="btn-subscribe-form" class="btn btn-submit"><?=$this->translate('Subscribe Now'); ?></a>
                </div>
            </div>
        </div>
    </section>
    <!---->
    <!---->
    <section class="section-padding wow fadeInUp delay-02s" id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-12">
                    <div class="section-title">
                        <h2 class="head-title"><?=$this->translate('Portfolio'); ?></h2>
                        <hr class="botm-line">
                        <p class="sec-para"><?=$this->translate('Portfolio Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..'); ?></p>
                    </div>
                </div>
                <div class="col-md-8 col-sm-12">
                    <?php 
                    for($i=1; $i<=4; $i++){     
                    ?>
                    <div class="col-md-6 col-sm-6 padding-right-zero">
                        <div class="portfolio-box design"> 
                            <img src="<?=$this->url('index').'img/'; ?>photo_500x300.jpeg" alt="" class="img-responsive">
                        </div>
                    </div>
                    <?php 
                    } 
                    ?>
                </div>
            </div>
        </div>
    </section>
    <!---->
      
    
    <!---->
    <section class="section-padding parallax bg-image-partners section wow fadeIn delay-08s" id="cta-2">
        <div class="container">
            <div class="row">
                <div class="col-md-12"> 
                    <div class="cta-txt text-center"> 
                        <h3><?=$this->translate('Our partners'); ?></h3>   
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id ligula felis euismod semper. </p>
                    </div>
                </div> 
                <?php 
                for($i=1; $i<=4; $i++){        
                ?>
                  <div class="col-xs-6 col-md-3 text-center partners-list">   
                    <div class="img-our-partners">     
                      <i class="fa fa-globe" aria-hidden="true"></i>
                    </div>
                  </div>  
                <?php
                }
                ?> 
            </div>
        </div>
    </section>
    <!---->
    
    <!---->
    <section class="section-padding wow fadeInUp delay-05s" id="contact">
        <div class="container">
            <div class="row white">
                <div class="col-md-8 col-sm-12">
                    <div class="section-title">
                        <h2 class="head-title black"><?=$this->translate('Contact Us'); ?></h2>
                        <hr class="botm-line">
                        <p class="sec-para black"><?=$this->translate('Contact Us Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..'); ?></p>
                    </div>
                </div>
                <div class="col-md-12 col-sm-12">
                    <div class="col-md-4 col-sm-6" style="padding-left:0px;">
                        <h3 class="cont-title"><?=$this->translate('Email Us'); ?></h3> 
                        <div id="contact-result"></div>
                        <div class="contact-info">
                            <form action="" method="post" role="form" class="contactForm">
                                <div class="form-group">
                                    <input type="text" name="name" class="form-control" id="contactus-name" placeholder="<?=$this->translate('Your Name'); ?>"/>
                                </div> 
                                <div class="form-group">
                                    <input type="email" class="form-control" name="email" id="contactus-email" placeholder="<?=$this->translate('Your Email'); ?>"/>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="subject" id="contactus-subject" placeholder="<?=$this->translate('Subject'); ?>"/>
                                </div>
                                
                                <div class="form-group"> 
                                    <textarea class="form-control" name="message" id="contactus-message" rows="5" placeholder="<?=$this->translate('Message'); ?>"></textarea>
                                </div> 
                                <button type="button" onclick="contactUs();" class="btn btn-send btn-loader"><i class="fa fa-paper-plane-o" aria-hidden="true"></i> <?=$this->translate('Send'); ?></button>
                            </form>
                        </div>
                        
                    </div>
                    <div class="col-md-4 col-sm-6">
                        <h3 class="cont-title"><?=$this->translate('Visit Us'); ?></h3>  
                        <div class="location-info">
                            <p class="white"><span aria-hidden="true" class="fa fa-map-marker"></span><?=$this->translate('Company address contact'); ?></p>   
                            <p class="white"><span aria-hidden="true" class="fa fa-phone"></span><?=$this->translate('Phone'); ?>: 03 44 87 87 23</p>
                            <p class="white"><span aria-hidden="true" class="fa fa-envelope"></span><?=$this->translate('Email'); ?>: <a href="" class="link-dec">mail@yourdomain.com</a></p>
                        </div>
                    </div> 
                    <div class="col-md-4">
                        <div class="contact-icon-container hidden-md hidden-sm hidden-xs"> 
                            <span aria-hidden="true" class="fa fa-envelope-o"></span>
                        </div>
                    </div>  
                </div>
            </div>
        </div>
    </section>  
    <!----> 
    <?php 
    include("footer.phtml"); 
    ?>
</div>