<div id="app">  
    <?php  
    include("header.phtml"); 
    ?> 
    <div class="content">      
        <section class="register">
            <div class="container"> 
            	<div class="row">
            		<div class="col-md-4 col-md-offset-4">
            			<div class="panel panel-default">  
            				<div class="panel-heading">
            					<h3 class="panel-title"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->translate('Login Title'); ?></h3> 
            				</div>
            				<div class="panel-body">  
            				    <div id="login-error"></div>   
            					<form id="login-form">  
            						<fieldset>
            							<div class="form-group">
											 <label class="sr-only" for="login-email"><?=$this->translate('Email address');?></label> 
											 <input type="email" class="form-control" id="login-email" placeholder="<?=$this->translate('Email address');?>" required>
										</div>
										<div class="form-group"> 
											<label class="sr-only" for="login-password"><?=$this->translate('Password');?></label>  
											<input type="password" class="form-control" id="login-password" placeholder="<?=$this->translate('Password');?>" required>
                                            <div class="help-block text-right">
                                                <a href="<?= $this->url('index').$lang.'/forgotpass'; ?>"><?=$this->translate('Forget the password ?');?></a> 
                                            </div>
										</div>
            							<button type="button" onclick="userLogin();" class="btn btn-lg btn-success btn-block btn-register btn-loader">
            								<i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->translate('Sign in');?>  
            							</button> 
            						</fieldset>  
            					</form> 
            					<hr/>   
            					<center>  
            						<h4><?=$this->translate('OR'); ?></h4>   
            					</center>
            					<button class="btn btn-lg btn-facebook btn-block btn-loader" id="loginBtn" type="button" onclick="loginFB();">
            						<i class="fa fa-facebook" aria-hidden="true"></i> <?=$this->translate('Login With Facebook'); ?> 
            					</button>
            					<?php 
            					if($action=='contract'){     
            					?>
            					<div class="help-block text-right"> 
                                    <a href="<?= $this->url('index').$lang.'/contract/'.$eid.'/?task=register'; ?>"><?=$this->translate('I am not a member yet.');?></a>  
                                </div>
                                <?php
            					}else{ 
                                ?>
                                <div class="help-block text-right"> 
                                    <a href="<?= $this->url('index').$lang.'/register'; ?>"><?=$this->translate('I am not a member yet.');?></a>  
                                </div>
                                <?php
            					}
                                ?>
            				</div>
            			</div>
            		</div>
            	</div>
            </div> 
        </section> 
        <!-- end regis -->  
    </div>
    
    <?php 
    include("footer.phtml"); 
    ?> 
    
</div>
 