<div id="app">  
    <?php  
    include("header.phtml"); 
    ?> 
    <div class="content">      
        <section class="register">
            <div class="container"> 
            	<div class="row">
            		 <div class="col-md-12"> 
            		     <div class="mission-block text-center">
            		          <div class="icon-send-block">
            		              <i class="fa fa-paper-plane-o" aria-hidden="true"></i> 
            		          </div>  
            		          <h1>The estimate was send</h1>   
            		          <p>You will be able to start the assingnment when the client has accepted and provisioned the amont. We'll keep you posted !</p>
            		          <a href="<?=$this->url('index').$lang.'/'; ?>supplier/" class="btn btn-primary btn-manage-mission">Manage My Missions</a>
            		     </div> 
            		 </div>
            	</div> 
            </div> 
        </section> 
        <!-- end regis -->  
    </div> 
    <?php 
    include("footer.phtml"); 
    ?> 
    
</div>
 