<div id="app">  
    <?php  
    include("header.phtml"); 
    ?> 
    <div class="content">    
        <section class="register" id="register">
            <div class="container"> 
            	<div class="row">
            		<div class="col-md-4 col-md-offset-4">
            			<div class="panel panel-default"> 
            				<div class="panel-heading">
            					<h3 class="panel-title"><i class="fa fa-user-plus" aria-hidden="true"></i> <?=$this->translate('Register Title'); ?></h3>
            				</div>
            				<div class="panel-body">
            				    <div id="register-display"></div> 
            					<form id="regis-form">
            						<fieldset>
            							<div class="form-group input-group">
            								<span class="input-group-addon"><i class="fa fa-user-o" aria-hidden="true"></i></span>
            								<input id="regis-name" name="fullname" type="text" placeholder="<?=$this->translate('Full Name'); ?>" class="form-control input-md" required="">
            							</div>
            							<div class="form-group input-group"> 
            								<span class="input-group-addon"><i class="fa fa-envelope-o" aria-hidden="true"></i></span>
            								<input class="form-control" placeholder="yourmail@example.com" id="regis-email" name="email" type="email">
            							</div>
            							<div class="form-group input-group">
            								<span class="input-group-addon"><i class="fa fa-key" aria-hidden="true"></i></span>
            								<input class="form-control" placeholder="<?=$this->translate('Password'); ?>" id="regis-password"  name="password" type="password" value="">
            							</div>
            							<div class="form-group input-group">
            								<span class="input-group-addon"><i class="fa fa-key" aria-hidden="true"></i></span>
            								<input id="regis-confirmpass" name="confirmpassword" type="password" placeholder="<?=$this->translate('Confirm Password'); ?>" class="form-control input-md">
            							</div>
            							  
										<div class="form-group input-group">  
										    <div class="g-recaptcha" data-sitekey="<?=$recaptcha['Site_key'];?>"></div>  
            							</div>  
            							
            							<div class="form-group"> 
                                            <div class="check_terms_block">   
                                              <div class="checkbox">     
                                                <input class="check_terms" type="checkbox" id="check_terms" name="check_terms">  
                                                <a href="<?= $this->url('index').$lang.'/terms'; ?>" target="_blank">      
    										         <?php echo $this->translate('I agree to the Terms of Service.'); ?>      
    										     </a>
                                              </div>
                                            </div>  
										</div>
										
            							<button  type="button" onclick="userRegister();"  class="btn btn-lg btn-success btn-block btn-register btn-loader">
            								<i class="fa fa-floppy-o" aria-hidden="true"></i> <?=$this->translate('Register'); ?> 
            							</button>
            						</fieldset>  
            					</form> 
            					<hr/> 
            					<center>
            						<h4><?=$this->translate('OR'); ?></h4>
            					</center>
            					<button class="btn btn-lg btn-facebook btn-block btn-loader" id="loginBtn" type="button" onclick="loginFB();">
            						<i class="fa fa-facebook" aria-hidden="true"></i> <?=$this->translate('Login With Facebook'); ?>
            					</button>  
            					<?php
            					if($action=='contract'){         
            					?>
            					<div class="help-block text-right">  
                                    <a href="<?= $this->url('index').$lang.'/contract/'.$eid.'/?task=login'; ?>"><?=$this->translate('I already have an account.');?></a>  
                                </div>
                                <?php 
            					}else{ 
                                ?>
                                <div class="help-block text-right">  
                                    <a href="<?= $this->url('index').$lang.'/login'; ?>"><?=$this->translate('I already have an account.');?></a>   
                                </div> 
                                <?php
            					}
                                ?>
            					
            				</div>
            			</div>
            		</div>
            	</div>
            </div> 
        </section> 
        <!-- end regis -->  
    </div>
    
    <?php 
    include("footer.phtml"); 
    ?> 
    
</div>
