<div id="app">  
    <?php  
    include("header.phtml");  
    ?> 
    <div class="content">     
        <section class="terms" id="terms"> 
            <div class="container"> 
            	<div class="row">   
            		<div class="col-md-12">
            		    <h1>Terms and service</h1>
            		    <div class="terms-content">
            		        <p>xxx xxx According to the total price, the duration of the contract different contracts can be issued automatically. 
    The element will include customer information and supplier information dynamically  xxx                                            <br>1. xxxx xxxx                                            <br>2.xxxx xxxx                                            <br>3.xxxx xxxx                                            <br>4.xxxx xxxx                                            <br>5.xxxx xxxx                                            <br>6.xxxx xxxx                                            <br>7.xxxx xxxx                                        </p>
            		    </div>
            		</div>	
            	</div>
            </div> 
        </section> 
        <!-- end regis -->  
    </div>
    <?php 
    include("footer.phtml");  
    ?> 
    
</div>
