<section class="pb_section" id="account-block">
    <div class="container-full">
    	<div class="row">
		    <div class="col-sm-12 col-md-6 col-lg-6"> 
		    	<div class="row">
			    	<div class="col-12 col-md-9 ml-md-auto mr-md-auto">
				      	<div class="panel panel-login"> 
							<div class="panel-heading">    
								<div class="row">
									<div class="col-sm-6 col-md-6 col-lg-6 col-mobile">
										<a href="#" class="header-tabs <?=($task=='' || $task=='login')?'active':'';?>" id="login-form-link"><?=$this->translate('Login'); ?></a>
									</div>  
									<div class="col-sm-6 col-md-6 col-lg-6 col-mobile">
										<a href="#" class="header-tabs <?=($task=='register')?'active':'';?>" id="register-form-link"><?=$this->translate('Register'); ?></a>
									</div> 
								</div>
							</div>  
							<div class="panel-body">     
							
								<form id="login-form" action="" method="post" role="form" style="display: <?=($task=='' || $task=='login')?'block':'none';?>;"> 
									<div class="form-group"> 
										<input type="email" name="email" id="login-email" class="form-control" placeholder="<?=$this->translate('E-mail'); ?>" value="<?=(!empty($email))?$email:'';?>" <?=(!empty($email) && $action=='contract')?'disabled':'';?>> 
									</div>  
									<div class="form-group">
										<input type="password" name="password" id="login-password"  class="form-control" placeholder="<?=$this->translate('Password'); ?>">
									</div>
									<div class="form-group">
										<button type="button" onclick="login();" class="btn btn-primary btn-lg btn-block btn-loader"><?=$this->translate('button login'); ?></button>
									</div>
									<div class="form-group"> 
										<div class="text-center">
											<a href="<?= $this->url('index').$lang.'/forgotpass'; ?>" tabindex="5" class="forgot-password"><?=$this->translate('Forgot Password?'); ?></a>
										</div>
									</div>
								</form>    
								
								<form id="register-form" action="" method="post" role="form" style="display: <?=($task=='register'  && $task!='')?'block':'none';?>;"> 
									<?php 
									if(!empty($buyer_id)){   
									?>
									<input type="hidden" name="buyer_id" id="buyer_id" value="<?=(!empty($buyer_id))?$buyer_id:'';?>">
									<?php
									}
									?>
									<div class="form-group">
										<input type="text" name="name" id="regis-name" tabindex="1" class="form-control" placeholder="<?=$this->translate('Name'); ?>" required="true" value="<?=(!empty($name))?$name:'';?>"> 
									</div> 
									<div class="form-group"> 
										<input type="email" name="email" id="regis-email" tabindex="1" class="form-control" placeholder="<?=$this->translate('E-mail'); ?>" required="true" value="<?=(!empty($email))?$email:'';?>" <?=(!empty($email) && $action=='contract')?'disabled':'';?>>
									</div>   
									<div class="form-group">
										<input type="password" name="password" id="input-password" tabindex="2" class="form-control" placeholder="<?=$this->translate('Password'); ?>"  required="true"> 
									</div>
									<div class="form-group">
										<input type="password" name="confirm-password" id="input-confirm-password" tabindex="2" class="form-control" placeholder="<?=$this->translate('Confirm Password'); ?>" required="true">
									</div>
									<div class="form-group"> 
										<button type="button" onclick="register();" class="btn btn-primary btn-lg btn-block btn-loader"><?=$this->translate('button register'); ?></button>
									</div> 
								</form>        
								<div class="row">  
									<div class="col-sm-12">
										<a class="btn btn-block btn-social btn-facebook btn-lg btn-block" href="javascript:connectUserFB();"> 
									    	<span class="fa fa-facebook"></span> <?=$this->translate('Sign in with Facebook'); ?>
									  	</a>
									</div> 
								</div>
							</div>
						</div>
					</div>
				</div>
		    </div>
		    <div class="col-sm-12 col-md-6 col-lg-6"> 
		    	<div class="row"> 
			      	<div class="col-12 col-md-10 ml-md-auto mr-md-auto">
			      		<div class="img-block-logo-regis">   
			      			<img src="<?=$this->url('index');?>2018/assets/images/wezenit-login-min.png" class="align-self-start" id="img-login" style="display: <?=($task=='' || $task=='login')?'block':'none';?>;"> 
			      			<img src="<?=$this->url('index');?>2018/assets/images/wezenit-register-min.png" class="align-self-start" id="img-regis" style="display: <?=($task=='register' && $task!='')?'block':'none';?>;">
			      		</div>  
			      	</div> 
			     </div> 
		    </div> 
		</div> 
   	</div> 
</section>
