<section class="pb_section text-center" id="contact-form">
    <div class="container-full">  
        <div class="row"> 
            <div class="col-sm-12 col-md-6 col-lg-6 ml-md-auto mr-md-auto bg-wezenit-form">
              <h4 class="heading mb-3 color-sky"><?=$this->translate('Questions ? Contact Us'); ?></h4>
              <p class="lead text-muted mb-3"><?=$this->translate('We respond within 24 hours'); ?></p>  
              <form action="" role="form" method="post" id="contactus-form">  
                <div class="form-group"> 
                  <input type="text" class="form-control" nane="name" id="name" autocomplete="off" placeholder="<?=$this->translate('Your name'); ?>">
                </div>      
                <div class="form-group">  
                  <input type="text" class="form-control" nane="email" id="email" autocomplete="off" placeholder="<?=$this->translate('Your email'); ?>">
                </div>
                <div class="form-group">  
                   <textarea class="form-control" name="message" id="message" placeholder="<?=$this->translate('Your message'); ?>" rows="5"></textarea> 
                </div> 
                <button type="button" onclick="sendContactUs();" class="btn btn-primary btn-lg btn-block btn-loader"><?=$this->translate('Contact Us'); ?></button>
              </form> 
            </div>
        </div> 
    </div>  
</section>
