<section class="pb_section">
    <div class="container"> 
    	<div class="row">  
    		<div class="col-md-12 mb-5">  
    		    <?php
    		    if($lang=='fr'){
    		    ?>
    		    <h3 class="title-faq mb-2 text-bold"><?=$this->translate('Foire Aux Questions'); ?></h3>
    			<p class="fs-16 text-gray-soft">Ici, nous donnons des réponses à vos questions</p>
    			
                <h4 class="heading-faq">Par quoi dois je commencer pour bénéficier de Wezenit ?</h4>
                <p>C’est très simple il vous suffit de créer un compte avec une adresse email et un mot de passe. La création de compte est gratuite</p>
                
                <h4 class="heading-faq">Et si mon acheteur ne paie pas ?</h4>
                <p>Aucun soucis. Wezenit se charge de relancer votre acheteur en lui indiquant le délai dans lequel il peut verser les fonds. Si l’acheteur ne verse pas les fonds dans le temps imparti vous restez libre de vendre votre produit à un autre acheteur ou de ne plus le vendre. Restez zen.</p>
                
                <h4 class="heading-faq">Et si mon produit n’arrive pas ?</h4>
                <p>Si votre produit n’arrive pas il vous suffit de nous l’indiquer en utilisant votre compte. Votre paiement restera bloqué jusqu’à la date refixée par l’outil. EN cas de défaut d’expédition ou de réception, vos fonds vous seront restitués selon votre contrat. Restez zen.</p>
                
                <h4 class="heading-faq">Je veux faire faire des travaux de rénovation et j'ai déjà un prestataire comment puis-je utiliser Wezenit ?</h4>
                <p>Wezenit s’occupe de tout. Vous n’avez qu’à renseigner les coordonnées de votre prestataire dans votre compte et Wezenit le contacte directement pour la mise en œuvre d’une « zentransaction ».</p>
                
                <h4 class="heading-faq">Mes travaux ont déjà commencé, comment faire ?</h4>
                <p>De la même manière que s’ils n’avaient pas commencé, en remplissant les coordonnées de votre prestataire dans votre compte Wezenit. Seuls les travaux et paiements effectués suite à la mise en œuvre de Wezenit seront sécurisés.</p>
                
                <h4 class="heading-faq">Est ce que je dois sélectionner mon prestataire/vendeur sur votre plateforme ?</h4>
                <p>Non. Wezenit sécurise tous vos contrats quel que soit votre prestataire. Son profil sera créé et vous devrez vous noter l’un l’autre à l’issue des travaux.</p>
                
                <h4 class="heading-faq">Mes fonds sont ils vraiment sécurisés ?</h4>
                <p>Votre contrat définit les conditions et dates à laquelle/auxquelles vos fonds sont versés au vendeur/prestataire. Vous avez la possibilité à tout moment de notifier Wezenit d’une raison sérieuse justifiant le non-paiement des fonds, conformément à votre contrat.</p>
                
                <h4 class="heading-faq">Et si je ne suis pas satisfait de l’objet de la transaction que se passe t'il ?</h4>
                <p>Vous devez notifier Wezenit grâce à votre compte, ce qui permet à l’autre partie d’apporter les éléments de réponse. Selon les cas, le processus peut générer le décalage de la date de paiement, un paiement partiel, total ou un remboursement total, ou partiel.</p>
                
                <h4 class="heading-faq">Que se passe t’il si mon acheteur cherche des raisons pour ne pas libérer le paiement ?</h4>
                <p>Avec Wezenit, la date de libération de paiement est fixée à l’avance. L’acheteur n’a plus à approuver le paiement. Celui-ci sera effectué, sauf si l’acheteur notifie Wezenit dans le délai prévu de la réalisation défectueuse de la prestation ou de l’absence du produit. Ce à quoi vous pourrez répondre pour permettre à la situation d’être résolue selon le processus « mediazen » de Wezenit.</p>
                
                <h4 class="heading-faq">En combien de temps Wezenit devient-il effectif ?</h4>
                <p>Instantanément à la réception des fonds. Acheteur et Vendeur/Prestataire sont notifiés dans le même temps par écrit.</p>
                
                <h4 class="heading-faq">Une fois les fonds versés est ce que je suis aidé ?</h4>
                <p>Bien sûr. Wezenit vous accompagne tout au long de votre transaction en s’assurant par des demandes régulières que le planning est bien respecté et en vous fournissant l’opportunité de répondre facilement et nous informer de toute modification.</p>
                
                <h4 class="heading-faq">Comment est ce que je communique avec Wezenit ?</h4>
                <p>Afin de bénéficier des services Wezenit la communication se fait avec votre compte Wezenit. Pour toute question vous pouvez également nous écrire à contact@wezenit.com ou nous appeler .</p>
                
                <h4 class="heading-faq">Et si je m’aperçois après la transaction que le produit n’est pas le bon ?</h4>
                <p>Wezenit garantit la disponibilité des fonds et leur paiement à la date définie, qui est toujours postérieure à la date de la transaction. Il appartient cependant aux parties de vérifier et agréer les conditions des produits et /ou services sur lequel/lesquels elles s’entendent.</p>
                
                <h4 class="heading-faq">Comment est-ce que Wezenit permet à tout le monde de travailler en confiance totale ?</h4>
                <p>Grâce à Wezenit, les professionnels confiants en leur qualité et honnêtes sont garantis du paiement total de leur prestation et leurs clients, honnêtes et prêts à payer pour le travail demandé le démontre en libérant les fonds à l’avance, tout en ne prenant aucun risque puisqu’en cas de non réalisation /mauvaise réalisation, les fonds sont restitués, en totalité ou partie selon le cas.</p>
                <?php
    		    }else{
                ?>
                <h3 class="title-faq mb-2 text-bold"><?=$this->translate('Frequently Asked Questions'); ?></h3>
    			<p class="fs-16 text-gray-soft">Here you’ll find the answers to all your questions</p>
    			
                <h4 class="heading-faq">How do I need to do to benefit from WeZenIt ?</h4>
                <p>It’s very simple. You just need to create your account with a valid email address and a password. It’s free so no worries.</p>
                 
                <h4 class="heading-faq">So what if the buyer does not transfer the funds to start the transaction ?</h4>
                <p>No worries at all. WeZenIt regularly informs your buyer of the time he has to send the funds to WeZenIt. Of course you are also kept informed at the same time. If the buyr does not transfer the funds you remain free to sell to whoever you want, not sell or reset new dates.</p>
                
                <h4 class="heading-faq">What if my product does not arrive ? </h4>
                <p>If the product does not arrive you just need to let us know with your WeZenIt account. No worries we send you reminders for that before the payment date. When we receive your notification payment is suspended until the reset date. If seller has not confirmed shipment or responded and if the product is not received, you get your money back (minus WeZenIt fee). Stay Zen.</p>
                
                <h4 class="heading-faq">I want to do home renovation and I already have selected a contractor, can I use WeZenIt ?</h4>
                <p>Of course ! WeZenIt is here to help you no matter what. In this case just log in to your account and create the transaction in WeZenIt providing your contractor’s details. We’ll contact him directly to secure the transaction in WeZenIt. As always, we keep you informed at very step.</p>
                
                <h4 class="heading-faq">The renovation or services have already started, can I use WeZenIt ?</h4>
                <p>Yes you can ! It works the same way. Create the transaction in WeZenIt providing your contractor’s details and we’ll do the rest. The works and payments will be guaranteed from the date WeZenIt has been effected by the transfer of funds.</p>
                
                <h4 class="heading-faq">Do I need to select my service provider or seller on your website ?</h4>
                <p>Absolutely not. You are free. WeZenIt secures all your contracts regardless of who you provider or client is (while in compliance with the law of course). The service provider (or client) you select will have to create his/her own profile and once the transaction is completed each one will provide the other with a review.</p>
                
                <h4 class="heading-faq">Is my money really safe with you ?</h4>
                <p>It’s a fair question. The contract you and the other party agree to defines precisely the date and conditions under which payment is released. At anytime before the payment set date you are free to inform us that the other party has defaulted and that payment shall not be made as per the contract. It won’t and the resolution process shall be implemented to address the situation.</p>
                
                <h4 class="heading-faq">What if I ‘m not satisfied with the product or services ?</h4>
                <p>In such case you only need to inform us through your WeZenIt account, so taht the other party can provide a response, details or any valid information. Depending on the situation, the resolution process may lead to postpone the payment date, provide for a partial or total payment or a partial or total reimbursement.</p>
                
                <h4 class="heading-faq">What if my buyer is trying to find excuses not to pay ?</h4>
                <p>With WeZenIt the payment date is preset in advance and the funds are not with the buyer anymore. So he/she does not have to approve the payment. Payment is made unless if the buyer notifies WeZenIt in the relevant period that the product or service is defective. In such case you will be notified at the same time and requested to respond which gives you the opportunity to demonstrate the product or service is fine and resolve the situation following the WeZenIt mediazen process. Remember after each transaction both parties issue a review of the other which will be on their public profile. No one has interest in messing around.</p>
                
                <h4 class="heading-faq">How long does it take for WeZenIt to become effective ?</h4>
                <p>It is instantaneous after we received the funds in full. Buyer and seller/provider are all informed at the same time.</p>
                
                <h4 class="heading-faq">Once I have transferred my money am I left alone or do I get assistance if needed ?</h4>
                <p>WeZenIt is at your side all along your transaction. We send you regular updates on the timeline and enquire frequently on how the transaction is doing to make sure all is on track as initially defined.  This offers you an easy way to respond and let us know how your transaction is doing and request potential changes.</p>
                
                <h4 class="heading-faq">How do I communicate with WeZenIt ?</h4>
                <p>Simply with your WeZenIt account. You can also contact us for any question at contact@wezenit.com or drop us a line.</p>
                
                <h4 class="heading-faq">What if I realize only after payment that my product is not the right one or is defective ?</h4>
                <p>Wezenit guarantees the availability of the transaction funds until the agreed payment date, which always takes place after the transaction itself. It is important that buyer and seller check and validate the conditions of the products / services they agr upon.  </p>
                
                
                <h4 class="heading-faq">How does WeZenIt allow everyone to work in full trust with one another ?</h4>
                <p>Thanks to WeZenIt honest businesses who are confident in the quality of their products and services are fully guaranteed to receive on-time total payment for the agreed work. Honest clients, ready to pay for what they requested so demonstrate by transferring funds ahead of the transaction to WeZenIt. In doing so they do not take any risk because if there are deficiencies the funds are reimbursed to the buyer. WeZenIt creates a virtuous cycle for all.</p>
                
                 
                <?php
    		    }
                ?>
    		</div>
    	</div>
    </div>
</section>     
