
<section class="pb_section" id="newpassword"> 
    <div class="container-full">   
        <div class="row">  
          <div class="col-sm-12 col-md-2 col-lg-2 mb-3"> 
            <?php
            include 'menu-profile.phtml'; 
            ?>  
          </div>
          <div class="col-sm-12 col-md-10 col-lg-10">
            <div class="row"> 
              <div class="col mb-5">
                <legend class="title color-sky mb-3"> 
  					<?=$this->translate('New Password'); ?>
  				</legend> 
      			<form class="form-horizontal" id="form-profile" name="form-newpass" action=""  method="post">
					<fieldset>
                        
						<div class="form-group">
							<label class="col-md-3 control-label" for="profile-oldpassword"><?=$this->translate('Old Password'); ?></label>
							<div class="col-md-6">
								<input id="profile-oldpassword" name="profile-oldpassword" type="password" placeholder="<?=$this->translate('Old Password'); ?>" class="form-control input-md">
							</div>
						</div>   

						<div class="form-group">
							<label class="col-md-3 control-label" for="profile-newpass"><?=$this->translate('New Password'); ?></label>
							<div class="col-md-6">
								<input id="profile-newpass" name="profile-newpass" type="password" placeholder="<?=$this->translate('New Password'); ?>" class="form-control input-md">
							</div>
						</div> 

						<div class="form-group">
							<label class="col-md-3 control-label" for="New Password"><?=$this->translate('Confirm Password'); ?></label>
							<div class="col-md-6">
								<input id="profile-confnewpass" name="profile-confnewpass" type="password" placeholder="<?=$this->translate('Confirm Password'); ?>" class="form-control input-md">
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-3 control-label" ></label>  
							<div class="col-md-6"> 
							    <button type="submit" onclick="newPassword();" class="btn btn-primary btn-loader"><i class="fa fa-floppy-o" aria-hidden="true"></i> <?=$this->translate('Change password'); ?></button> 
							</div>
						</div>    

					</fieldset>
				</form>
              </div>
          </div>
       </div>  
    </div>  
</section>   