<section class="pb_section text-center" id="forgotpass-form">
    <div class="container-full">
        <div class="row"> 
            <div class="col-sm-12 col-md-6 col-lg-6 ml-md-auto mr-md-auto bg-wezenit-form">
              <h4 class="heading mb-5 color-sky"><i class="fa fa-key" aria-hidden="true"></i> <?=$this->translate('Register'); ?></h4>
            </div> 
        </div> 
        <div class="row">  
            <div class="col-sm-12 col-md-6 col-lg-4 ml-md-auto mr-md-auto bg-wezenit-form"> 
                <input type="hidden" name="id" id="id" value="<?=$userProfile->id;?>"/>  
                <input type="hidden" name="name" id="name" value="<?=$userProfile->name;?>"/>
                <input type="hidden" name="email" id="email" value="<?=$userProfile->email;?>"/>
                <input type="hidden" name="login-email" id="login-email" value="<?=$userProfile->email;?>"/>
                <input type="hidden" name="login-password" id="login-password" value=""/>
                <div class="form-group"> 
                    <input type="email" class="form-control" name="email" id="email" value="<?=$userProfile->email;?>" placeholder="<?=$this->translate('E-mail'); ?>" required="" disabled/>
          		</div>
                <div class="form-group">
          			<input id="password" name="password" type="password" placeholder="<?=$this->translate('Password'); ?>" class="form-control" required=""> 
          		</div>
          		<hr>  
          		<button type="button" onclick="newpasswordRegis();" class="btn btn-primary btn-lg btn-block btn-loader">	<i class="fa fa-floppy-o" aria-hidden="true"></i> <?=$this->translate('Save'); ?></button>
  		    </div> 
        </div>  
    </div>  
</section>   