<section class="pb_section text-center" id="contact-form">
    <div class="container-full">  
        <div class="row"> 
            <div class="col-sm-12 col-md-6 col-lg-6 ml-md-auto mr-md-auto bg-wezenit-form">
              <h4 class="heading mb-3 color-sky"><?=$this->translate("Our team"); ?></h4> 
              <p class="lead text-muted mb-5"><?=$this->translate("A reactive team at your service"); ?></p> 
            </div> 
        </div>   
        <div class="row justify-content-md-center">
          <div class="col-sm-12 col-md-6 col-lg-2 user-team"> 
            <div class="img-user-team" style="background:url(<?=$this->url('index');?>2018/assets/images/person-2.png) top center no-repeat; background-size:cover;"></div>
            <p class="text-name">Nicolas Simon</p>
            <p class="text-position">Zen Master</p>
          </div> 
          <div class="col-sm-12 col-md-6 col-lg-2 user-team"> 
            <div class="img-user-team" style="background:url(<?=$this->url('index');?>2018/assets/images/person-1.png) top center no-repeat; background-size:cover;"></div>
            <p class="text-name">Charles Doligé</p>
            <p class="text-position">Commercial guru</p>
          </div> 
          <div class="col-sm-12 col-md-6 col-lg-2 user-team"> 
            <div class="img-user-team" style="background:url(<?=$this->url('index');?>2018/assets/images/person-3.png) top center no-repeat; background-size:cover;"></div>
            <p class="text-name">Thibaut Lacave</p>
            <p class="text-position">Web magician</p>
          </div> 
          <div class="col-sm-12 col-md-6 col-lg-2 user-team"> 
            <div class="img-user-team" style="background:url(<?=$this->url('index');?>2018/assets/images/person-4.png) top center no-repeat; background-size:cover;"></div>
            <p class="text-name">Sylvain De Muynck</p>
            <p class="text-position">Techno Wizard</p>
          </div> 
        </div> 
        
        <?php
        if(0){
        ?>
        <div class="row"> 
            
             <div class="col-sm-12 col-md-6 col-lg-6 mb-3">
              <div class="card border-0 mb-4"> 
                <a href="#" class="pb_hover-zoom image-popup image-block"> 
                  <img class="img-fluid" src="<?=$this->url('index');?>2018/assets/images/person-2.png" alt="Image caption here">
                  <p class="lead text-muted text-hever">Nicolas Simon</p>
                                    <p class="lead text-muted text-hever">CEO & Founder</p>

                </a>
              </div>
            </div> 
            
            <div class="col-sm-12 col-md-6 col-lg-4  mb-3">
              <div class="card border-0 mb-4">  
                <a href="#" class="pb_hover-zoom image-popup image-block">
                  <img class="img-fluid" src="<?=$this->url('index');?>2018/assets/images/person-1.png" alt="Image caption here">
                  <p class="lead text-muted text-hever">Charles Doligé</p>
                </a>
              </div>
            </div> 
            
            <div class="col-sm-12 col-md-6 col-lg-4 mb-3"> 
              <div class="card border-0 mb-4">
                <a href="#" class="pb_hover-zoom image-popup image-block">
                  <img class="img-fluid" src="<?=$this->url('index');?>2018/assets/images/person-3.png" alt="Image caption here">
                  <p class="lead text-muted text-hever">Thibaut Lacave</p>
                </a>
              </div>
            </div> 
            <div class="col-sm-12 col-md-6 col-lg-4 mb-3">
              <div class="card border-0 mb-4">
                <a href="#" class="pb_hover-zoom image-popup image-block">
                  <img class="img-fluid" src="<?=$this->url('index');?>2018/assets/images/person-4.png" alt="Image caption here">
                  <p class="lead text-muted text-hever">Sylvain De Muynck</p>
                </a>
              </div>
            </div>
        </div>
        <?php
        }
        ?>
    </div>  
</section>   