<p><strong>1. Pr&eacute;sentation du site</strong></p>

<p>Merci de lire avec attention les diff&eacute;rentes modalit&eacute;s d&rsquo;utilisation du pr&eacute;sent site avant d&rsquo;en parcourir ses pages. En vous connectant sur ce site, vous acceptez sans r&eacute;serves les pr&eacute;sentes modalit&eacute;s.</p>

<p>En vertu de l&#39;article 6 de la loi n&deg; 2004-575 du 21 juin 2004 pour la confiance dans l&#39;&eacute;conomie num&eacute;rique, il est pr&eacute;cis&eacute; aux utilisateurs du site <a href="http://www.wezenit.com">www.wezenit.com</a> :</p>

<p>Propri&eacute;taire : Zenovly &nbsp;SAS, RCS Paris 828 377 697 &ndash; 36, rue de Laborde, 75008 PARIS</p>

<p>Cr&eacute;ateur: Wezenit SAS</p>

<p>Responsables publication: Zenovly SAS &ndash; contact@wezenit.com</p>

<p>Le responsable publication est une personne physique ou une personne morale.</p>

<p>Webmaster: Zenovly</p>

<p>H&eacute;bergeur: Amazon EC2_</p>

<p>Cr&eacute;dits : Zenovly SAS</p>

<p>
	<br>
</p>

<p><strong>2. Conditions g&eacute;n&eacute;rales d&rsquo;utilisation du site et des services propos&eacute;s</strong></p>

<p>L&rsquo;utilisation du site &quot;www.wezenit.com&quot; implique l&rsquo;acceptation pleine et enti&egrave;re des conditions g&eacute;n&eacute;rales d&rsquo;utilisation ci-apr&egrave;s d&eacute;crites. Ces conditions d&rsquo;utilisation sont susceptibles d&rsquo;&ecirc;tre modifi&eacute;es ou compl&eacute;t&eacute;es &agrave; tout moment, les utilisateurs du site &quot;www.wezenit.com&quot; sont donc invit&eacute;s &agrave; les consulter de mani&egrave;re r&eacute;guli&egrave;re.</p>

<p>Ce site est normalement accessible &agrave; tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut &ecirc;tre toutefois d&eacute;cid&eacute;e par Wezenit, qui s&rsquo;efforcera alors de communiquer pr&eacute;alablement aux utilisateurs les dates et heures de l&rsquo;intervention.</p>

<p>Le site &quot;www.wezenit.com&quot; est mis &agrave; jour r&eacute;guli&egrave;rement par Wezenit. De la m&ecirc;me fa&ccedil;on, les mentions l&eacute;gales peuvent &ecirc;tre modifi&eacute;es &agrave; tout moment : elles s&rsquo;imposent n&eacute;anmoins &agrave; l&rsquo;utilisateur qui est invit&eacute; &agrave; s&rsquo;y r&eacute;f&eacute;rer le plus souvent possible afin d&rsquo;en prendre connaissance.</p>

<p>Les conditions d&rsquo;utilisation des services payants sont soumis aux conditions sp&eacute;cifiques d&rsquo;utilisation des services (&laquo;&nbsp;CGUS&nbsp;&raquo;) accessibles &agrave; la cr&eacute;ation de votre compte.</p>

<p>
	<br>
</p>

<p><strong>3. Description des services fournis</strong></p>

<p>Le site &quot;www.wezenit.com&quot; a pour objet de fournir une information concernant l&rsquo;ensemble des activit&eacute;s de la soci&eacute;t&eacute; et les services que la soci&eacute;t&eacute; propose &agrave; ses utilisateurs.</p>

<p>Wezenit s&rsquo;efforce de fournir sur le site &quot;www.wezenit.com&quot; des informations aussi pr&eacute;cises que possible. Toutefois, ils ne pourront &ecirc;tre tenu responsables des omissions, des inexactitudes et des carences dans la mise &agrave; jour, qu&rsquo;elles soient de leur fait ou du fait des tiers partenaires qui leur fournissent ces informations.</p>

<p>Tous les informations indiqu&eacute;es sur le site &quot;www.wezenit.com&quot; sont donn&eacute;es &agrave; titre indicatif, et sont susceptibles d&rsquo;&eacute;voluer. Par ailleurs, les renseignements figurant sur le site &quot; www.wezenit.com&quot; ne sont pas exhaustifs. Ils sont donn&eacute;s sous r&eacute;serve de modifications ayant &eacute;t&eacute; apport&eacute;es depuis leur mise en ligne.</p>

<p>
	<br>
</p>

<p><strong>4. Limitations contractuelles sur les donn&eacute;es techniques.</strong></p>

<p>Le site utilise la technologie JavaScript.</p>

<p>Le site Internet ne pourra &ecirc;tre tenu responsable de dommages mat&eacute;riels li&eacute;s &agrave; l&rsquo;utilisation du site. De plus, l&rsquo;utilisateur du site s&rsquo;engage &agrave; acc&eacute;der au site en utilisant un mat&eacute;riel r&eacute;cent, ne contenant pas de virus et avec un navigateur de derni&egrave;re g&eacute;n&eacute;ration mis-&agrave;-jour.</p>

<p>
	<br>
</p>

<p><strong>5. Propri&eacute;t&eacute; intellectuelle et contrefa&ccedil;ons.</strong></p>

<p>Wezenit est propri&eacute;taire des droits de propri&eacute;t&eacute; intellectuelle ou d&eacute;tient les droits d&rsquo;usage sur tous les &eacute;l&eacute;ments accessibles sur le site, notamment les textes, images, graphismes, logo, ic&ocirc;nes, sons, logiciels.</p>

<p>Toute reproduction, repr&eacute;sentation, modification, publication, adaptation de tout ou partie des &eacute;l&eacute;ments du site, quel que soit le moyen ou le proc&eacute;d&eacute; utilis&eacute;, est interdite, sauf autorisation &eacute;crite pr&eacute;alable de Wezenit.</p>

<p>Toute exploitation non autoris&eacute;e du site ou de l&rsquo;un quelconque des &eacute;l&eacute;ments qu&rsquo;il contient sera consid&eacute;r&eacute;e comme constitutive d&rsquo;une contrefa&ccedil;on et poursuivie conform&eacute;ment aux dispositions des articles L.335-2 et suivants du Code de Propri&eacute;t&eacute; Intellectuelle.</p>

<p>
	<br>
</p>

<p><strong>6. Limitations de responsabilit&eacute;.</strong></p>

<p>Wezenit ne pourra &ecirc;tre tenue responsable des dommages directs et indirects caus&eacute;s au mat&eacute;riel de l&rsquo;utilisateur, lors de l&rsquo;acc&egrave;s au site www.wezenit.com, et r&eacute;sultant soit de l&rsquo;utilisation d&rsquo;un mat&eacute;riel ne r&eacute;pondant pas aux sp&eacute;cifications indiqu&eacute;es au point 4, soit de l&rsquo;apparition d&rsquo;un bug ou d&rsquo;une incompatibilit&eacute;.</p>

<p>Wezenit ne pourra &eacute;galement &ecirc;tre tenue responsable des dommages indirects (tels par exemple qu&rsquo;une perte de march&eacute; ou perte d&rsquo;une chance) cons&eacute;cutifs &agrave; l&rsquo;utilisation du site &quot;www.wezenit.com&quot;</p>

<p>Des espaces interactifs (possibilit&eacute; de poser des questions dans l&rsquo;espace contact) sont &agrave; la disposition des utilisateurs. Wezenit se r&eacute;serve le droit de supprimer, sans mise en demeure pr&eacute;alable, tout contenu d&eacute;pos&eacute; dans cet espace qui contreviendrait &agrave; la l&eacute;gislation applicable en France, en particulier aux dispositions relatives &agrave; la protection des donn&eacute;es. Le cas &eacute;ch&eacute;ant, Wezenit se r&eacute;serve &eacute;galement la possibilit&eacute; de mettre en cause la responsabilit&eacute; civile et/ou p&eacute;nale de l&rsquo;utilisateur, notamment en cas de message &agrave; caract&egrave;re raciste, injurieux, diffamant, ou pornographique, quel que soit le support utilis&eacute; (texte, photographie&hellip;).</p>

<p>
	<br>
</p>

<p><strong>7. Gestion des donn&eacute;es personnelles.</strong></p>

<p>En France, les donn&eacute;es personnelles sont notamment prot&eacute;g&eacute;es par la loi n&deg; 78-87 du 6 janvier 1978, la loi n&deg; 2004-801 du 6 ao&ucirc;t 2004, l&#39;article L. 226-13 du Code p&eacute;nal et la Directive Europ&eacute;enne du 24 octobre 1995.</p>

<p>A l&#39;occasion de l&#39;utilisation du site &quot;www.wezenit.com&quot; peuvent &ecirc;tres recueillies : l&#39;URL des liens par l&#39;interm&eacute;diaire desquels l&#39;utilisateur a acc&eacute;d&eacute; au site &quot;www.wezenit.com&quot; le fournisseur d&#39;acc&egrave;s de l&#39;utilisateur, l&#39;adresse de protocole Internet (IP) de l&#39;utilisateur.</p>

<p>En tout &eacute;tat de cause Wezenit ne collecte pas d&rsquo;informations personnelles relatives &agrave; l&#39;utilisateur autre que pour le besoin de certains services propos&eacute;s par le site &quot; www.wezenit.com&quot; L&#39;utilisateur fournit ces informations en toute connaissance de cause, notamment lorsqu&#39;il proc&egrave;de par lui-m&ecirc;me &agrave; leur saisie. Il est alors pr&eacute;cis&eacute; &agrave; l&#39;utilisateur du site &quot;www.wezenit.com&quot; l&rsquo;obligation ou non de fournir ces informations.</p>

<p>Conform&eacute;ment aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative &agrave; l&rsquo;informatique, aux fichiers et aux libert&eacute;s, tout utilisateur dispose d&rsquo;un droit d&rsquo;acc&egrave;s, de rectification et d&rsquo;opposition aux donn&eacute;es personnelles le concernant, en effectuant sa demande &eacute;crite et sign&eacute;e, accompagn&eacute;e d&rsquo;une copie du titre d&rsquo;identit&eacute; avec signature du titulaire de la pi&egrave;ce, en pr&eacute;cisant l&rsquo;adresse &agrave; laquelle la r&eacute;ponse doit &ecirc;tre envoy&eacute;e.</p>

<p>Aucune information personnelle de l&#39;utilisateur du site &quot;www.wezenit.com&quot; n&#39;est publi&eacute;e &agrave; l&#39;insu de l&#39;utilisateur, &eacute;chang&eacute;e, transf&eacute;r&eacute;e, c&eacute;d&eacute;e ou vendue sur un support quelconque &agrave; des tiers. Seule l&#39;hypoth&egrave;se du rachat &agrave; Wezenit de ses actifs permettrait la transmission des dites informations &agrave; l&#39;&eacute;ventuel acqu&eacute;reur qui serait &agrave; son tour tenu de la m&ecirc;me obligation de conservation, confidentialit&eacute; et de modification des donn&eacute;es vis &agrave; vis de l&#39;utilisateur du site &quot;www.wezenit.com&quot;</p>

<p>Le site n&#39;est pas d&eacute;clar&eacute; &agrave; la CNIL car il ne recueille pour l&rsquo;instant pas d&#39;informations personnelles.</p>

<p>Les bases de donn&eacute;es sont prot&eacute;g&eacute;es par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative &agrave; la protection juridique des bases de donn&eacute;es.</p>

<p>
	<br>
</p>

<p><strong>8. Liens hypertextes et cookies.</strong></p>

<p>Le site &quot;www.wezenit.com&quot; contient un certain nombre de liens hypertextes vers d&rsquo;autres sites, mis en place avec l&rsquo;autorisation de Wezenit . Cependant, Wezenit n&rsquo;a pas la possibilit&eacute; de v&eacute;rifier le contenu des sites ainsi visit&eacute;s, et n&rsquo;assumeront en cons&eacute;quence aucune responsabilit&eacute; de ce fait.</p>

<p>La navigation sur le site &quot;www.wezenit.com&quot; est susceptible de provoquer l&rsquo;installation de cookie(s) sur l&rsquo;ordinateur de l&rsquo;utilisateur. Un cookie est un fichier de petite taille, qui ne permet pas l&rsquo;identification de l&rsquo;utilisateur, mais qui enregistre des informations relatives &agrave; la navigation d&rsquo;un ordinateur sur un site. Les donn&eacute;es ainsi obtenues visent &agrave; faciliter la navigation ult&eacute;rieure sur le site, et ont &eacute;galement vocation &agrave; permettre diverses mesures de fr&eacute;quentation.</p>

<p>Le refus d&rsquo;installation d&rsquo;un cookie peut entra&icirc;ner l&rsquo;impossibilit&eacute; d&rsquo;acc&eacute;der &agrave; certains services. L&rsquo;utilisateur peut toutefois configurer son ordinateur de la mani&egrave;re suivante, pour refuser l&rsquo;installation des cookies :</p>

<p>Sous Internet Explorer : onglet outil (pictogramme en forme de rouage en haut a droite) / options internet. Cliquez sur Confidentialit&eacute; et choisissez Bloquer tous les cookies. Validez sur Ok.</p>

<p>
	<br>
</p>

<p>Sous Firefox : en haut de la fen&ecirc;tre du navigateur, cliquez sur le bouton Firefox, puis aller dans l&#39;onglet Options. Cliquer sur l&#39;onglet Vie priv&eacute;e.</p>

<p>Param&eacute;trez les R&egrave;gles de conservation sur : utiliser les param&egrave;tres personnalis&eacute;s pour l&#39;historique. Enfin d&eacute;cochez-la pour d&eacute;sactiver les cookies.</p>

<p>Sous Safari : Cliquez en haut &agrave; droite du navigateur sur le pictogramme de menu (symbolis&eacute; par un rouage). S&eacute;lectionnez Param&egrave;tres. Cliquez sur Afficher les param&egrave;tres avanc&eacute;s. Dans la section &quot;Confidentialit&eacute;&quot;, cliquez sur Param&egrave;tres de contenu. Dans la section &quot;Cookies&quot;, vous pouvez bloquer les cookies.</p>

<p>Sous Chrome : Cliquez en haut &agrave; droite du navigateur sur le pictogramme de menu (symbolis&eacute; par trois lignes horizontales). S&eacute;lectionnez Param&egrave;tres. Cliquez sur Afficher les param&egrave;tres avanc&eacute;s. Dans la section &quot;Confidentialit&eacute;&quot;, cliquez sur pr&eacute;f&eacute;rences. Dans l&#39;onglet &quot;Confidentialit&eacute;&quot;, vous pouvez bloquer les cookies.</p>

<p>
	<br>
</p>

<p><strong>9. Droit applicable et attribution de juridiction.</strong></p>

<p>Tout litige en relation avec l&rsquo;utilisation du site &quot;www.wezenit.com&quot; est soumis au droit fran&ccedil;ais. Il est fait attribution exclusive de juridiction aux tribunaux comp&eacute;tents de Paris.</p>

<p>
	<br>
</p>

<p><strong>10. Contestations&nbsp;</strong></p>

<p>Si vous souhaitez signaler un non-respect des droits de propri&eacute;t&eacute; intellectuelle dont vous seriez titulaire, le non-respect d&rsquo;une r&egrave;gle qui vous cause un pr&eacute;judice &eacute;crivez-nous &agrave; <a href="mailto:contact@wezenit.com">contact@wezenit.com</a>.</p>

<p>
	<br>
</p>

<p><strong>11. Lexique.</strong></p>

<p>
	<br>
</p>

<p>Utilisateur : Internaute se connectant, utilisant le site susnomm&eacute;.</p>

<p>Informations personnelles : &laquo; les informations qui permettent, sous quelque forme que ce soit, directement ou non, l&#39;identification des personnes physiques auxquelles elles s&#39;appliquent &raquo; (article 4 de la loi n&deg; 78-17 du 6 janvier 1978).</p>


<p id="mangopay"><strong>12. Terms & conditions de Mangopay .</strong></p>
Vous pouvez lire les terms & conditions de MangoPay <a href="https://www.mangopay.com/terms/MANGOPAY_Terms-FR.pdf" target="_blank"> en cliquant ici  </a>
<a href="https://www.mangopay.com/privacy/" target="_blank"><img src="https://www.mangopay.com/terms/powered-by-mangopay.png" class="img-responsive" style="max-width: 300px;"></img></a>

