<div class="panel panel-default">
    <div class="panel-heading">  
        New Blog
        <a href="<?php echo $this->url('index').'admin/blog/';?>" class="btn btn-success btn-xs pull-right"><i class="fa fa-undo" aria-hidden="true"></i>Back</a>
    </div>
    <div class="panel-body"> 
        <form action="<?php echo $this->url('index').'admin/blog/?task=add';?>" enctype="multipart/form-data" name="blogform" id="blogform" method="post">
        	<div class="box-body">
        	    
            	<div class="form-group">
          			<label for="name">Language</label> 
          			<select class="form-control" id="lang" name="lang">
          			    <option value="1">French</option>
          			    <option value="2">English</option>
          			</select>
        		</div> 
        		<div id="block-fr"> 
        		    <div class="form-group">
              			<label for="name">Title Fr</label>
              			<input type="text" class="form-control" id="name" name="blog[name]" placeholder="title">
            		</div>
            		<div class="form-group">
              			<label for="detail">Detail Short Fr</label>   
              		    <textarea name="blog[detail_short]" class="form-control" id="detail_short" rows="5"></textarea>  
              		</div>
            		<div class="form-group"> 
              			<label for="detail">Detail Fr</label>   
              		    <textarea name="blog[detail]" class="form-control summernote" id="detail" rows="5"></textarea>  
              		</div> 
        		</div>
        		
        		<div id="block-en" style="display:none;">
        		    <div class="form-group">
              			<label for="name">Title En</label>
              			<input type="text" class="form-control" id="name_en" name="blog[name_en]" placeholder="title">
            		</div>
            		<div class="form-group">
              			<label for="detail">Detail Short En</label>   
              		    <textarea name="blog[detail_short_en]" class="form-control" id="detail_short_en" rows="5"></textarea>  
              		</div>
            		<div class="form-group"> 
              			<label for="detail">Detail En</label>   
              		    <textarea name="blog[detail_en]" class="form-control summernote" id="detail_en" rows="5"></textarea>  
              		</div> 
        		</div>
          		
          		<div class="form-group">
          			<label for="pic">Image size:480x480px</label>  
          			<input type="file" id="pic" name="pic" onchange="imagePreview(this,'img-preview', 100)">
        			<div id="img-preview"></div>    
        		</div> 
                <div class="form-group"> 
                    <label for="active">Status</label><br> 
          			<input type="checkbox" name="active" id="active" value="0">     
        		</div>     
      		</div><!-- /.box-body -->
            <hr /> 
      		<div class="box-footer">
        		<button type="button" onclick="validateform();" class="btn btn-primary">Submit</button>
      		</div>
    	</form> 
    </div> 
</div> 