<div class="panel panel-default">
    <div class="panel-heading">  
        Blog List
        <a href="<?php echo $this->url('index').'admin/blog/?task=add';?>" class="btn btn-success btn-xs pull-right"><i class="fa fa-newspaper-o" aria-hidden="true"></i> New</a>
    </div>   
    <!-- /.panel-heading --> 
    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTable"> 
            <thead> 
                <tr> 
                    <th>#</th>
                    <th>Photo</th>
                    <th>Name</th>
                    <th>View</th> 
                    <th>Last Update</th>
                    <th>Status</th>
                    <th>Action</th> 
                </tr>
            </thead>
            <tbody> 
            </tbody>
        </table>
    </div>  
    <!-- /.panel-body -->
</div>
<!-- /.panel --> 
<script type="text/javascript">
$(function(){    
    table = $('#dataTable').DataTable( {
        //ajax: basePath+'admin/blog/?task=list&rd='+makeid(),  
        "ajax": {
            url: basePath+'admin/blog/?task=list&rd='+makeid(),
            dataSrc: function(d){ 
             return d.result;     
            },
        }, 
        "iDisplayLength": 50, 
        "bSort": false, 
        "serverSide": true,
        "processing": true, 
        aLengthMenu: [ 
            [50, 100, 300, 500], 
            [50, 100, 300, 500]  
        ],  
        columns: [ 
            { "data": null, 
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                   var pageNo = table.page.info(); 
                   //console.log(((iRow+1)+pageNo.start)); 
                   $(nTd).html(((iRow+1)+pageNo.start));    
                },  
            },
            { "data": null, 
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    var url_img = basePath+'img/noimage.png';   
                    if(sData.img){  
                        url_img = '<?=$urlFile;?>/blog/'+sData.img;  
                    }  
                    $(nTd).html('<img src="'+url_img+'" style="max-width:100px;">'); 
                    
                },
            },
            { "data": "name" }, 
            { "data": null, 
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    var view = view + 100;
                    $(nTd).html(numberFormat(sData.view));     
                },
            },
            { "data": "last_update" }, 
            { "data": null, 
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    var status = '<span class="label label-warning">inactive</span>'; 
                    if(oData.active == 1) status = '<span class="label label-success">active</span>';
                    $(nTd).html(status);    
                },
            }, 
            
            { "data": null, 
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {  
                    var html = ''; 
                    html += ' <a class="btn btn-primary btn-xs" href="'+basePath+'admin/blog/'+oData.id+'?task=image"><i class="fa fa-photo"></i>  Image</a> ';
                    html += ' <a class="btn btn-info btn-xs" href="'+basePath+'admin/blog/'+oData.id+'?task=edit"><i class="fa fa-edit"></i>  Edit</a> ';
                    html += ' <a class="btn btn-danger btn-xs btn-loader" href="'+basePath+'admin/blog/'+oData.id+'?task=del"onclick="return confirm(\'Are you sure you want to delete. !\');" ><i class="fa fa-trash-o"></i>  Delete</a> ';
                    $(nTd).html(html);      
                },
            }, 
        ], 
        createdRow : function( row, data, index ) { 
            //$(row).attr('data-id', data.pkbook);
        }
    }); 
});
</script>