<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <?php 
                    if(!empty($error)){   
                    ?>
                    <div class="alert alert-danger"> 
                      <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                      <strong>Authentication failed.</strong> 
                    </div>  
                    <?php
                    }
                    ?>
                    <form role="form" method="post"  name="quest" action="<?php echo $this->url('index').'admin/login/';?>">
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="E-mail" name="email" type="email" value="<?=$email;?>" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="password" type="password" value="">
                            </div>
                            <div class="checkbox">
                                <label> 
                                    <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                </label>
                            </div> 
                            <!-- Change this to a button or input when using this as a form -->
                            <button type="submit" class="btn btn-lg btn-success btn-block">Login</button> 
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div> 
</div>

<?php
if(0){
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->url('index') . 'css/admin-login.css?2017-03-07-1'; ?>" /> 
          
<div class="wrapper">    
    <form class="form-signin" method="post" onSubmit="return checkLogin()" name="quest" action="<?php echo $this->url('index').'admin/login/';?>">           
      <h1 class="form-signin-heading">Please login</h1>   
      <input type="email" value="<?=$email;?>" class="form-control" name="email" placeholder="Email Address" required="" autofocus="" />
      <input type="password" class="form-control" name="password" placeholder="Password" required=""/>      
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>    
    </form>  
</div>   
<?php
}
?>