<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span> 
    </button>
    <a class="navbar-brand" href="<?php echo $this->url('index').'admin/';?>">Wezenit</a> 
</div>
<!-- /.navbar-header -->
<ul class="nav navbar-top-links navbar-right">  
    <li> 
        <a href="<?php echo $this->url('index');?>" target="_blank"><i class="fa fa-life-ring" aria-hidden="true"></i> View Site</a>  
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i><span><?=$admin->name;?></span> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">  
            <li>
                <a href="<?php echo $this->url('index').'admin/admin/'.$admin->id.'?task=edit';?>"><i class="fa fa-user fa-fw"></i> User Profile</a>
            </li>
            <li class="divider"></li> 
            <li>
                <a href="<?php echo $this->url('index').'admin/logout/';?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->