<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
                </div>
                <!-- /input-group --> 
            </li>
            <li> 
                <a href="<?php echo $this->url('index').'admin/';?>"  class="<?=$action=='index'?'active':'';?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>  
            </li>
            <li>
                <a href="<?php echo $this->url('index').'admin/users/';?>" class="<?=$action=='admin'?'in-active':'';?>"><i class="fa fa-user" aria-hidden="true"></i> Users</a>
            </li>
            <?php
            if($admin->level==1){  
            ?>
            <li>
                <a href="<?php echo $this->url('index').'admin/admin/';?>" class="<?=$action=='admin'?'in-active':'';?>"><i class="fa fa-user-secret" aria-hidden="true"></i> Admin</a>
            </li>
            <?php 
            }
            ?>
            <li> 
                <a href="<?php echo $this->url('index').'admin/blog/';?>" class="<?=$action=='blog'?'active':'';?>"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Blog</a>  
            </li>
            <li> 
                <a href="<?php echo $this->url('index').'admin/contract/';?>" class="<?=$action=='contract'?'active':'';?>"><i class="fa fa-compress" aria-hidden="true"></i> Contract</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Payment<span class="fa arrow"></span></a> 
                <ul class="nav nav-second-level">  
                    <li>  
                        <a href="<?php echo $this->url('index').'admin/paybuyer/';?>">Pay the buyer</a>   
                    </li>     
                    <li>  
                        <a href="<?php echo $this->url('index').'admin/payrefund/';?>">Refund</a>   
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <?php
            if($admin->level==1){  
            ?>
            <li>
                <a href="<?php echo $this->url('index').'admin/setting/';?>" class="<?=$action=='setting'?'in-active':'';?>"><i class="fa fa-cogs" aria-hidden="true"></i> Setting</a>
            </li>
            
            <?php
            }  
            if(0){ 
            ?>
            <li>
                <a href="<?php echo $this->url('index').'admin/cmspage/';?>" class="<?=$action=='cmspage'?'in-active':'';?>"><i class="fa fa-life-ring" aria-hidden="true"></i> CMS Page</a>
            </li> 
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="flot.html">Flot Charts</a>
                    </li>
                    <li>
                        <a href="morris.html">Morris.js Charts</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
            </li>
            <li>
                <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="panels-wells.html">Panels and Wells</a>
                    </li>
                    <li>
                        <a href="buttons.html">Buttons</a>
                    </li>
                    <li>
                        <a href="notifications.html">Notifications</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                    <li>
                        <a href="icons.html"> Icons</a>
                    </li>
                    <li>
                        <a href="grid.html">Grid</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Third Level <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                        </ul>
                        <!-- /.nav-third-level -->
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="blank.html">Blank Page</a>
                    </li>
                    <li>
                        <a href="login.html">Login Page</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li> 
            <?php
            } 
            ?>
            <li> 
                <a href="<?php echo $this->url('index').'admin/logout/';?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->