<div class="panel panel-default">
    <div class="panel-heading">  
        Users List
        <a href="<?php echo $this->url('index').'admin/users/?task=add';?>" class="btn btn-success btn-xs pull-right"><i class="fa fa-user-plus" aria-hidden="true"></i> New</a>
    </div> 
    <!-- /.panel-heading --> 
    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTable"> 
            <thead> 
                <tr> 
                    <th>#</th>
                    <th>Photo</th>
                    <th>Name</th>
                    <th>Email</th> 
                    <th>Type</th>
                    <th>Create Date</th>
                    <th>Status</th>
                    <th>Action</th> 
                </tr>
            </thead>
            <tbody> 
            </tbody>
        </table>
    </div>  
    <!-- /.panel-body -->
</div>
<!-- /.panel --> 
<script type="text/javascript">
$(function(){    
    table = $('#dataTable').DataTable( {
        ajax: basePath+'admin/users/?task=list&rd='+makeid(),  
        iDisplayLength: 50,
        "bSort": false, 
        "serverSide": true,
        "processing": true, 
        aLengthMenu: [ 
            [50, 100, 300, 500], 
            [50, 100, 300, 500]  
        ],  
        columns: [
            { "data": null, 
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                   var pageNo = table.page.info(); 
                   //console.log(((iRow+1)+pageNo.start)); 
                   $(nTd).html(((iRow+1)+pageNo.start));    
                },  
            },
            { "data": null, 
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    var url_img = basePath+'img/noimage.png';  
                    if(sData.image){ 
                        url_img = '<?=$urlFile;?>/users/'+sData.image;   
                    }  
                    $(nTd).html('<img src="'+url_img+'" style="max-width:100px;">');    
                },
            }, 
            { "data": "name" }, 
            { "data": "email" },  
           
            { "data": null, 
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    var type = 'User';  
                    if(oData.type == 2) type = 'Supplier';   
                    $(nTd).html(type);      
                },
            }, 
            { "data": "createdate" },
            { "data": null, 
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    var status = '<span class="label label-warning">inactive</span>'; 
                    if(oData.active == 1) status = '<span class="label label-success">active</span>';
                    $(nTd).html(status);    
                },
            }, 
            
            { "data": null, 
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {  
                    var html = '';   
                    if(oData.type==2) html += ' <a class="btn btn-primary btn-xs" href="'+basePath+'admin/users/'+oData.id+'?task=company"><i class="fa fa-home"></i>  Company</a> '; 
                    html += ' <a class="btn btn-info btn-xs" href="'+basePath+'admin/users/'+oData.id+'?task=edit"><i class="fa fa-edit"></i>  Edit</a> ';
                    html += ' <a class="btn btn-danger btn-xs" href="'+basePath+'admin/users/'+oData.id+'?task=del"onclick="return confirm(\'Are you sure you want to delete. !\');" ><i class="fa fa-trash-o"></i>  Delete</a> ';
                    $(nTd).html(html);      
                },
            }, 
        ], 
        createdRow : function( row, data, index ) { 
            //$(row).attr('data-id', data.pkbook);
        }
    }); 
});
</script>