<div class="panel panel-default">
    <div class="panel-heading">  
        Edit User
        <a href="<?php echo $this->url('index').'admin/users/';?>" class="btn btn-success btn-xs pull-right"><i class="fa fa-undo" aria-hidden="true"></i>Back</a>
        
    </div>
    <div class="panel-body"> 
        
        <form action="<?php echo $this->url('index').'admin/users/'.$id.'?task=edit';?>" enctype="multipart/form-data" name="registration" id="registration" method="post">
        	<div class="box-body">
            	<div class="form-group">  
                  	<label>Type</label> 
                  	<select class="form-control" name="user[type]">
                    	<option value="1" <?=($detail['type']==1)?'selected':'';?>>User</option>
                        <option value="2" <?=($detail['type']==2)?'selected':'';?>>Supplier</option>
                    </select>
                </div>
                <div class="form-group">   
                  	<label>Gender</label> 
                  	<select class="form-control" name="user[gender]">
                    	<option value="1" <?=($detail['gender']==1)?'selected':'';?>>Male</option>
                        <option value="2" <?=($detail['gender']==2)?'selected':'';?>>Female</option>    
                        <option value="0" <?=($detail['gender']==0)?'selected':'';?>>Other</option> 
                    </select>
                </div>
        		<div class="form-group">
          			<label for="exampleInputEmail1">Name</label>
          			<input type="text" class="form-control" id="name" name="user[name]" placeholder="Name" value="<?=(!empty($detail['name']))?$detail['name']:'';?>">
        		</div>
                <div class="form-group">
          			<label for="exampleInputEmail1">Email</label>
          			<input type="email" class="form-control" id="email" name="user[email]" placeholder="Email" value="<?=(!empty($detail['email']))?$detail['email']:'';?>">
        		</div>
        		<div class="form-group">
          			<label for="password">Password</label>
          			<input type="password" class="form-control" id="password" name="user[password]" placeholder="Password" value=""> 
        		</div>
                <div class="form-group">
          			<label for="exampleInputEmail1">Phone</label> 
          			<input type="text" class="form-control" id="phone" name="user[phone]" placeholder="Phone" value="<?=(!empty($detail['phone']))?$detail['phone']:'';?>"> 
        		</div> 
        		
        		<div class="form-group">
          			<label for="birth_day">Birth Day</label>  
          			<input type="text" class="form-control datepicker" id="birth_day" name="user[birth_day]" placeholder="Birth Day" value="<?=(!empty($detail['birth_day']))?$detail['birth_day']:date("Y-m-d");?>" readonly>
        		</div>
        		
        		<div class="form-group">
          			<label for="address">Address</label>
          			<textarea rows="4" class="form-control" id="address" name="user[address]" placeholder="Address"><?=(!empty($detail['address']))?$detail['address']:'';?></textarea>
        		</div> 
        		
        		<div class="form-group">  
          			<label for="exampleInputFile">Image size:200x200px</label> 
          			<input type="file" id="pic" name="pic" onchange="imagePreview(this,'img-preview', 100)">
        			<div id="img-preview">
        			    <?php
        			    if(!empty($detail['image'])){     
        			    ?>
        			    <br> 
        			    <img src="<?php echo $urlFile.'/users/'.$detail['image'];?>" style="max-width:200px;" /> 
        			    <?php
        			    } 
        			    ?>
        			</div>   
        		</div>  
                <div class="form-group">    
                    <label for="active">Status</label><br>
          			<input type="checkbox" name="active" id="active" value="<?=(!empty($detail['active']))?$detail['active']:'';?>" <?=($detail['active']==1)?'checked':'';?>>       
        		</div>    
      		</div><!-- /.box-body --> 
            <hr /> 
      		<div class="box-footer">
        		<button type="submit" class="btn btn-primary">Submit</button>
      		</div>
    	</form> 
    </div>  
</div>
<script type="text/javascript">  
$(function() { 
  $("form[name='registration']").validate({ 
    rules: {
     'admin[name]': "required", 
     'admin[email]': { 
        required: true,
        email: true
      }
    },  
    messages: { 
      'admin[name]': "Please enter your name",
      'admin[email]': "Please enter a valid email address" 
    },
    submitHandler: function(form) {
      form.submit();
    }
  }); 
});

</script>